### ISSUE TITLE
Potential simplification of hexagon midpoint calculation possible

### ISSUE THREAD

**Issue by chanana** [JustGlowing/minisom#102]
In your [Hexagonal topology example](https://github.com/JustGlowing/minisom/blob/master/examples/HexagonalTopology.ipynb), the fourth code cell contains the line:

```python
wy = wy * 2 / np.sqrt(3) * 3 / 4
``` 

which could perhaps be simplified to 

```python
wy = wy * np.sqrt(3) / 2
``` 
since we're trying to find the midpoint of the hexagon for the markers (presumably). There is a similar calculation further down concerning the `yticks` that could also be cleaned up similarly. Sorry, I realize that this is a really minor point but it confused me until I wrote it out on paper. It might be helpful to someone else too, especially since this is such a useful little script!
I would be happy to submit a quick PR with the changes if you'd like!

**Comment by JustGlowing** [comment]
hi @chanana, well spotted. Feel free to raise a PR if you want.
