### ISSUE TITLE
Can I change rectangular grid to hexagonal grid?

### ISSUE THREAD

**Issue by 4daJKong** [JustGlowing/minisom#106]
Hello,

Sorry to bother you. Is your minisom based on rectangular grid, right? I was wondering if change to hexagonal grid by adjusting some parameters...

Thanks

**Comment by JustGlowing** [comment]
Hi there, MiniSom supports hexagonal topology. Check out the example: https://github.com/JustGlowing/minisom/blob/master/examples/HexagonalTopology.ipynb
