### ISSUE TITLE
Normalizing distance with the number of neighbors

### ISSUE THREAD

**Issue by lbugnon** [JustGlowing/minisom#107]
I think it is more straightforward if the distance map is normalized by the number of neighbours (thus border and corner neurons have similar distance computations as the central ones). If you agree I can make a pull request

**Comment by JustGlowing** [comment]
hi @lbugnon that is a very nice observation. I would still keep as default the current normalization for backwards compatibility and add a new parameter to normalize as you suggest.

A PR would be very much appreciated. Here are the guidelines to contribute: https://github.com/JustGlowing/minisom/#guidelines-to-contribute
