### ISSUE TITLE
Run the model on GPU

### ISSUE THREAD

**Issue by djeffkanda** [JustGlowing/minisom#110]
Is it possible with the current implementation to run the experiment on a GPU?
What is the best choice of the grid size?

**Comment by JustGlowing** [comment]
hi @djeffkanda 

There's currently no way to run MiniSom on a GPU, I'm planning to add this features but it doesn't seem likely to happen in the near future.

There's a rule of thumb to pick the grid size: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L95

Keep in mind that it's just a rule of thumb and that the grid size needs to be optimized against the metric that is relevant to your application (quantization error, cluster homogeneity, precision, recall, ... this really depends on what you're trying to do)
