### ISSUE TITLE
"one iteration per sample"

### ISSUE THREAD

**Issue by jriege555** [JustGlowing/minisom#113]
Hello Giuseppe,

first of all thank you for this very nice and helpful implementation.

Before looking at your code in more detail I assumed that one iteration of the algorithm would mean updating the som n times if n is the number of input vectors. I just realized that one iteration means updating the som only once according to the chosen input vector and its relation to the weights' current state.

I am sure there is a good explanation for handling it this way but wouldn't handling it the other way lead to a smaller dependence between the order of the input vectors and the resulting som since the learning rate etc decrease with each iteration?

I hope I could make my thoughts clear.

**Comment by JustGlowing** [comment]
hi @jriege555 

It would indeed. If that what you want you have two ways to achieve that with minisom 1) Design a custom decay function 2) Override the train method with the logic that you prefer.

**Comment by jriege555** [comment]
Hi,

thank you for your reply, I will do exactly that. 

Since I am going to implement those modifications for myself anyway, are they of relevance for you and/or this repository?

**Comment by JustGlowing** [comment]
Of course, if you submit a pull request make sure you read the following guidelines

https://github.com/JustGlowing/minisom#guidelines-to-contribute
