### ISSUE TITLE
What's the point of normalizing all the rows at initialization time

### ISSUE THREAD

**Issue by phphong** [JustGlowing/minisom#12]
Line 51 of `minisom.py`:
```python
self.weights = array([v/linalg.norm(v) for v in self.weights]) # normalization
```
Each `v` is a matrix representing a whole row in the SOM map. It has "SOM-width" rows, and "input_len" columns. And `linalg.norm(v)` calculates the Frobenius Norm of that matrix. I wonder what's the point of normalizing this whole matrix, instead of just normalizing each element vector in the SOM map.

**Comment by JustGlowing** [comment]
It didn't make sense. I just commited a change where I implement the normalization element by element.

Thanks for your contributions.
