### ISSUE TITLE
What is the maximum size of data that can be used?

### ISSUE THREAD

**Issue by aryamaan3** [JustGlowing/minisom#121]
Hello, 
I am trying to implement minisom on my time series data, but am getting an unusual error. 
mySeries is a matrix of dimensions 88 * 1440
som_x, som_y are 4

```
som_x = som_y = math.ceil(math.sqrt(math.sqrt(len(mySeries))))
som = MiniSom(som_x, som_y, len(mySeries[0]), sigma=0.3, learning_rate = 0.1)

som.random_weights_init(mySeries)
som.train(mySeries, 2000)
```

This is the error

`Length of values (4) does not match length of index (1440)`

Is this due to the high length of the data?

and aren't the N used to determine the amount of categories (in this case 4*4) ?

<img width="974" alt="Screenshot 2021-11-16 at 18 28 43" src="https://user-images.githubusercontent.com/71285263/142035346-cf36db7f-f306-4edb-ba07-6095dc7df96b.png">

Thanks for your help!

**Comment by JustGlowing** [comment]
hi there, make sure that `input_len` is the number of columns in your data in input.

Also, keep in mind that you're passing to minisom a pandas `Series` which is one dimensional. See the example in the readme to check how to pass data to minisom.

**Comment by aryamaan3** [comment]
Oh okay, my data was wrongly dimensioned.
Thanks for the help!
