### ISSUE TITLE
support for strings

### ISSUE THREAD

**Issue by emanuelevivoli** [JustGlowing/minisom#123]
Hi @JustGlowing and thanks for the great repo!
I'm interested in applying the SOM on string elements, calculating distances using edit-distance or similar. 
What I see here is that all neurons are numerical, and so every neuro-input operation is calculated as numerical operations.
Do you have any advice for changing your `minisom` and extending it to my needs?
Thank you in advance :)

**Comment by JustGlowing** [comment]
hi @emanuelevivoli 

You could transform your text using a vectorial representation. This is an example of how to use the tf-idf representation:

https://github.com/JustGlowing/minisom/blob/master/examples/TopicModeling.ipynb

**Comment by emanuelevivoli** [comment]
Thanks for your suggestion, actually It doesn't fit my needs, but I found a way to do it by using [t-sne](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html) and passing it a distances matrix.
