### ISSUE TITLE
How to get indices of neurons

### ISSUE THREAD

**Issue by SandroMartens** [JustGlowing/minisom#124]
Hi,

I need the distance matrix of my prototypes. So I use `SOM._distance_from_weights(data)` to get this. But how can I assign these to my two dimensional topology? Like `prototype_Id: 0, Index: (0, 0)`. Just reshape to the original dimensions?

Thanks

**Comment by JustGlowing** [comment]
hi there, reshape is the best way. Have a look at this test: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L689
