### ISSUE TITLE
Time Series 

### ISSUE THREAD

**Issue by jaybhiesantos** [JustGlowing/minisom#125]
Hello! 
I am trying to use my time series data for the example uploaded, but I encounter this error when initializing pca. Also, the second image is the error that I encounter when I use random initialization. 

![image](https://user-images.githubusercontent.com/92415406/150127337-bf312034-ce39-4c77-869b-ecab14a262ed.png)
![image](https://user-images.githubusercontent.com/92415406/150127427-4ed88d54-f43f-479e-b5ea-cfa23f0c1556.png)

**Comment by jaybhiesantos** [comment]
Oh okay, but my data has only one column. How can I initialize the weights
if i cannot use pca? Sorry, im just new to this

**Comment by jaybhiesantos** [comment]
[image: image.png]

**Comment by JustGlowing** [comment]
If your data has only one column, you can use a random initialization. Just make sure that you pass a numpy array with 2 dimensions (checkout the reshape function).

Also, have a look at the example about working with time series data in the examples folder.

**Comment by jaybhiesantos** [comment]
I am basing my experiment on the example, but my data has a shape of 2207,1
so I am having trouble reshaping it into 2 dimensions.
Thank you

**Comment by jaybhiesantos** [comment]
Thank you so much for the help! It is working now

**Comment by JustGlowing** [comment]
amazing :-)

**Comment by jaybhiesantos** [comment]
[image: image.png]
but i cannot see the graph

**Comment by JustGlowing** [comment]
I can't see the image you tried to post.

**Comment by jaybhiesantos** [comment]
here
[image: image.png]
