### ISSUE TITLE
cannot import name 'Minisom' from 'minisom' (C:\Users\Username\anaconda3\lib\site-packages\minisom.py)

### ISSUE THREAD

**Issue by VishnuRamD** [JustGlowing/minisom#128]
How to solve this import error?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_36828/4140886123.py in <module>
      1 # minisom
----> 2 from minisom import Minisom
      3 from sklearn.datasets import load_breast_cancer
      4 import time

ImportError: cannot import name 'Minisom' from 'minisom' (C:\Users\Username\anaconda3\lib\site-packages\minisom.py)

**Comment by JustGlowing** [comment]
hi there,

How did you install minisom?

This are the instructions if you want to use pip: https://github.com/JustGlowing/minisom#installation

**Comment by VishnuRamD** [comment]
Yes I used pip install minisom only

**Comment by JustGlowing** [comment]
Make sure that the pip your are using is the one tied to the python used to run your script.

This can help: https://docs.python.org/3/tutorial/venv.html

**Comment by VishnuRamD** [comment]
Oh My bad I used Lower case "s" in MiniSom. Anyway thanks for quick response

**Comment by BaseMax** [comment]
Thanks
