### ISSUE TITLE
Train SOM module and then test it in unseen data

### ISSUE THREAD

**Issue by PauloAxcel** [JustGlowing/minisom#132]
Lets say I have one Dataframes, df1 
I created the following variables:

X_train = df.1values
y_train = df1.index.values

The index of each dataframe has information on the class of the datapoint
I set up the SOM

som = MiniSom(neuron,neuron, df.shape[1], sigma=1.5, learning_rate=.5, 
                  neighborhood_function='gaussian', random_seed=0)
som.pca_weights_init(X_train)
som.train(X_train, neuron*3000, verbose=True)  # random training

Now  I save this model, and load it onto another problem, which I do not know the classes of the datapoints (ie y_test = unknonw = indices of the dataframe)

X_test = df2.values
y_test = df2.index.values

Now I want to find where the X_test data points fall into the som we have developed from the df1 dataset. So I run the following

winmap = som.labels_map(X_train, y_train)

result = []
    for X in X_test:
        win_position = som.winner(X)
        if win_position in winmap:
            result.append(....)
        else:
            result.append(...)

This all works well. Now the problem is, imagine that I didn't want to load the X_train and y_train again, and just use the som to map out the winning neuron? Is there any way to do it? I have been testing everything and I can't do it, it seems that you need to have a winmap from the som labelled with the Xtrain and ytrain data. Is this true or is there any workaround?

**Comment by JustGlowing** [comment]
hi @PauloAxcel , winmap is a dictionary. Once you save it somewhere you can delete the training data.

**Comment by PauloAxcel** [comment]
Hello! Thank you for the reply,

So basically, I can save the winmap (.txt, .csv, ect), and then load it together with the som to do a proper analysis on some unseen data without having to load again the training data?

**Comment by JustGlowing** [comment]
Exactly, `json.dump()` provides a handy way to save a dictionary. Here's the documentation: https://docs.python.org/3/library/json.html
