### ISSUE TITLE
How to use Pandas?

### ISSUE THREAD

**Issue by gabriel-OFV** [JustGlowing/minisom#133]
I have a pandas dataset, how can I use SOM with it? As well as to save cluster centers to each group

**Comment by JustGlowing** [comment]
You can use MiniSom with dataframes as follows:

```
data = my_dataframe.values
som.train(data)
```

This is an example of how to do clustering and inspect the centers: https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

**Comment by gabriel-OFV** [comment]
Thank you!

Another question, how do I assign for each ID/Cliente his cluster node?

**Comment by JustGlowing** [comment]
Look at the example above please.

**Comment by JustGlowing** [comment]
In that example there's an array called cluster_index. It's what you're after.

**Comment by gabriel-OFV** [comment]
Yes... but I'm beginner at SOM, can you help me to create a column in my dataset to each ID cluster / node?
