### ISSUE TITLE
How to find type 1 and type 2 errors

### ISSUE THREAD

**Issue by TryBlueFly** [JustGlowing/minisom#143]
Please tell me how can I understand that the class is incorrectly defined by the neural network? And how to understand that it is correctly defined? Does this show quantization error?
My maps looks like that:
![image](https://user-images.githubusercontent.com/102958349/174798437-4e8528bd-9065-49fd-a6bd-cecc0c7ffcd9.png)

**Comment by JustGlowing** [comment]
A SOM is properly trained when similar samples (hopefully belonging to the same class) are mapped closely.

The quantization error alone is not able to tell if the SOM represents the data in the way you wish.

Have a look here:
- https://github.com/JustGlowing/minisom/blob/master/examples/BasicUsage.ipynb

Regarding Type 1 / Type 2 errors, you need to have a classification problem. This example can help:
- https://github.com/JustGlowing/minisom/blob/master/examples/Classification.ipynb
