### ISSUE TITLE
How to get the u-matrix and heat-map for a clustering problem?

### ISSUE THREAD

**Issue by alireza04** [JustGlowing/minisom#149]
According to [this question](https://github.com/JustGlowing/minisom/issues/64), I noticed that it is possible to use clustering to cluster the data points. However, in case there is no label data, is it possible to draw heatmap and u-matrix to identify correlations between input variables?

**Comment by JustGlowing** [comment]
sure you can, the answer is here https://github.com/JustGlowing/minisom/issues/78
