### ISSUE TITLE
Topographic error wrong for hexagonal topography with rectangular grid

### ISSUE THREAD

**Issue by mbarison** [JustGlowing/minisom#152]
Hi,

I am trying to get the topographic error from a SOM with 11x7 neurons, hexagonal topography.

When I do, I get this error:

```File ~/DEIL_ISC/2021-2022/5-Processing/On-Reserve Facilities/1-CSD_Compare/TopographicError.py:23, in TopographicError.<locals>._get_euclidean_coordinates_from_index(som, index)
     21     return (-1, -1)
     22 y = som._weights.shape[1]
---> 23 coords = som.convert_map_to_euclidean((index % y, int(index/y)))
     24 return coords

File ~/.local/lib/python3.8/site-packages/minisom.py:243, in MiniSom.convert_map_to_euclidean(self, xy)
    237 def convert_map_to_euclidean(self, xy):
    238     """Converts map coordinates into euclidean coordinates
    239     that reflects the chosen topology.
    240 
    241     Only useful if the topology chosen is not rectangular.
    242     """
--> 243     return self._xx.T[xy], self._yy.T[xy]

IndexError: index 8 is out of bounds for axis 1 with size 7
```

I don't  think [this line of code](https://github.com/JustGlowing/minisom/blob/9a5415a176fde35400eaed57f70d5c51a22c60f1/minisom.py#L594) makes sense:

`coords = som.convert_map_to_euclidean((index % y, int(index/y)))`

Shouldn't the parameters be inverted, e.g.:

 `coords = som.convert_map_to_euclidean((int(index/y), index % y))`

Anyway, thanks for the amazing work!

**Comment by JustGlowing** [comment]
Hi there, it's hard to help you with the details you shared. Check that the
dimensions are what you expect and make sure that the indexing respects it.

**Comment by JustGlowing** [comment]
This must be bug then. I'll reopen the issue. Unfortunately I don't have time to fix this in the short term.

**Comment by JustGlowing** [comment]
A correction, I can't replicate this error as I'm able to compute the topographic error using the hexagonal topology under different setups. You need to share more details about your situation if you want any support with this.

**Comment by JanDetroy** [comment]
Hey,
Thanks for the super fast reply. I create a som, initialise it with weights according to the pca and train it. Afterwards I try to compute the topographic error which results in the out of bounds error. This is the code that I am running: 
```
som_size = [6,5]
som = MiniSom(som_size[0], som_size[1], np.size(data,1), sigma=1.5, learning_rate=0.8,topology='hexagonal')
som.pca_weights_init(data)
som.train(data_sel, 100000,verbose=False,random_order=True)

te = som.topographic_error(data)
```
I think the issue might be in the following line:
https://github.com/JustGlowing/minisom/blob/9a5415a176fde35400eaed57f70d5c51a22c60f1/minisom.py#L566

The bmu that is calculated has an index that is bigger than my actual som size.

**Comment by JanDetroy** [comment]
> I don't think [this line of code](https://github.com/JustGlowing/minisom/blob/9a5415a176fde35400eaed57f70d5c51a22c60f1/minisom.py#L594) makes sense:
> 
> `coords = som.convert_map_to_euclidean((index % y, int(index/y)))`
> 
> Shouldn't the parameters be inverted, e.g.:
> 
> `coords = som.convert_map_to_euclidean((int(index/y), index % y))`
> 
> Anyway, thanks for the amazing work!

The change from above fixed the issue for me!

**Comment by XiaoXiaoLeisure** [comment]
> > I don't think [this line of code](https://github.com/JustGlowing/minisom/blob/9a5415a176fde35400eaed57f70d5c51a22c60f1/minisom.py#L594) makes sense:
> > `coords = som.convert_map_to_euclidean((index % y, int(index/y)))`
> > Shouldn't the parameters be inverted, e.g.:
> > `coords = som.convert_map_to_euclidean((int(index/y), index % y))`
> > Anyway, thanks for the amazing work!
> 
> The change from above fixed the issue for me!

I meet the same issue, and I solve it by change the code as well!

**Comment by JustGlowing** [comment]
@XiaoXiaoLeisure would you like to submit a pull request with your changes?

**Comment by XiaoXiaoLeisure** [comment]
> @XiaoXiaoLeisure would you like to submit a pull request with your changes?

I will try to submit a pull request.

**Comment by JustGlowing** [comment]
Thanks for pointing this out. I've just pushed the change.
