### ISSUE TITLE
Pip latest version is 2.3.0 (no hexagonal topographic error)

### ISSUE THREAD

**Issue by Unu-tech** [JustGlowing/minisom#153]
Good day to you!

Thank you for clean and functional implementation. Just a quick note here in case it's forgotten.

The [minisom.py](https://github.com/JustGlowing/minisom/blob/9a5415a176fde35400eaed57f70d5c51a22c60f1/minisom.py#L560-L575) file already has topographic error function implemented for hexagonal topography. However, when calling `som.topographic_error(data)`, it outputs:
_NotImplementedError: Topographic error not implemented for hexagonal topology._

**Comment by JustGlowing** [comment]
hi @Unu-tech, make that you are using the latest version of minisom. You can do that by running the following command

```
pip install minisom -U
```
