### ISSUE TITLE
Meaning of num_iteration inside train method

### ISSUE THREAD

**Issue by drkj10** [JustGlowing/minisom#154]
Hello,

I have a question please about the method : 
som.train_random(data = X, num_iteration = 100)
In this case, use_epochs=False.

What is the exact meaning of num_iteration ? 
What about the update of the radius(sigma) ?
What are the instructions applied to the first row of dataset before going to the second row ?

Thank you very much indeed.

Karim

**Comment by JustGlowing** [comment]
hi Karim,

Please refer to the documentation: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L395

To details about how `num_iterations` affects sigma and how the updates are performed, have a look at this method: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L337

Regards

**Comment by drkj10** [comment]
Hi,

Thank you very much for your response.

I read the documentation but I need your confirmation please. It is not clear for me.

When use_epochs=False, we apply at each iteration before passing to the second row the following instruction. At the first iteration, we update the weights of all the points inside the circle whose radius is sigma. At the second iteration, the same instruction but using sigma(t) = sigma / (1 + t/T). At the end of num_iteration, we pass to the next row. In other words, each 'Best Matching Unit' is treated num_iteration times before passing to the next BMU.

Best regards.

Karim
