### ISSUE TITLE
is there a way to find out clusters with minisom?

### ISSUE THREAD

**Issue by marifegitim** [JustGlowing/minisom#158]
Dear Mr/Mrs/Miss,

I am trying to cluster my country dataset like DemocracyIndex.ipynb example. The difference between my dataset and democracy index example is, I have no labels column(full democracy, authoritarian, etc.) I am trying to cluster the countries according to other variable columns.  

Is there a way/algorithm/library to find such clusters? I would be very thankful if you recommend me an algorithm or a way with minisom package.

Best Regards

**Comment by JustGlowing** [comment]
hi there, this example will give you an idea of how to do it: https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

**Comment by marifegitim** [comment]
Dear JustGlowing,
First of all, I am very thankful for your reply.

On this clustering example, as I investigate, cluster number is given by som_shape to cluster data and calculate centroids of each cluster. 

How can we perform such operation without knowing cluster size?

To be clear, I can create distance map like democracyIndex, but I could not find how to draw cluster boundaries. Is there a method for interpreting distance map and draw cluster boundries?

Best Regards.

**Comment by JustGlowing** [comment]
You can pick the number of clusters based on your prior knowledge on the data or using a heuristic (like the elbow rule https://glowingpython.blogspot.com/2019/01/a-visual-introduction-to-gap-statistics.html).

Regarding drawing cluster boundaries form the distance map, there are many approaches. The simplest one is to cluster the weights of the SOM.

Regards
