### ISSUE TITLE
Question on the radius.

### ISSUE THREAD

**Issue by mr-d3falt** [JustGlowing/minisom#162]
Does the radius gradually decrease with each iteration in the minisom SOM algorithm?

Thank you.

**Comment by youyinnn** [comment]
I think this is how the neighbourhood radius decreases the interaction alone.

https://github.com/JustGlowing/minisom/blob/e2efa8ece45260bf4335d99dedb32e34b1ae569a/minisom.py#L339
And the decay function is the `asymptotic_decay`.

Here's the plot of `plt.plot([asymptotic_decay(0.5, i, 1000) for i in range(1000)])`.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/23525754/223023852-ba171231-af9b-486f-b751-85975d797908.png">

**Comment by JustGlowing** [comment]
@mr-d3falt the radius is defined as sigma and it decreases at each training step as described here: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L116
