### ISSUE TITLE
How can I get reproducible results?

### ISSUE THREAD

**Issue by YixinNJU** [JustGlowing/minisom#164]
Hi, I am using SOM to do clustering analysis. After that, I calculate metrices to evaluate the performance (Silhouette value and so on), I find the performance metrices changed when I rerun SOM. I then pick the matrices belonging to the same SOM node and composite (average) them for both two runs. I find them differ. I am wondering why this would happen? Is there any way to make the results reproducible? Thank you!

**Comment by JustGlowing** [comment]
hi @YixinNJU, you can set the parameter `random_seed ` to a given integer.

**Comment by YixinNJU** [comment]
> hi @YixinNJU, you can set the parameter `random_seed ` to a given integer.

Thank you! It works!
