### ISSUE TITLE
considerations on the hexagonal neighborhood used in `distance_map()`

### ISSUE THREAD

**Issue by Pedro-V** [JustGlowing/minisom#166]
Hello! And congratulations for the library.

## Description

I was taking a look at the `MiniSom.distance_map` method, which on the first part, with a SOM $n \times m$, builds a matrix where the $i$-th row represents the distances around the $i$-th neuron.

The important lines of the method are the following

```python
        um = nan * zeros((self._weights.shape[0],
                          self._weights.shape[1],
                          8))  # 2 spots more for hexagonal topology

        ii = [[0, -1, -1, -1, 0, 1, 1, 1]]*2
        jj = [[-1, -1, 0, 1, 1, 1, 0, -1]]*2

        if self.topology == 'hexagonal':
            ii = [[1, 1, 1, 0, -1, 0], [0, 1, 0, -1, -1, -1]]
            jj = [[1, 0, -1, -1, 0, 1], [1, 0, -1, -1, 0, 1]]

        for x in range(self._weights.shape[0]):
            for y in range(self._weights.shape[1]):
                w_2 = self._weights[x, y]
                e = y % 2 == 0   # only used on hexagonal topology
                for k, (i, j) in enumerate(zip(ii[e], jj[e])):
                    if (x+i >= 0 and x+i < self._weights.shape[0] and
                            y+j >= 0 and y+j < self._weights.shape[1]):
                        w_1 = self._weights[x+i, y+j]
                        um[x, y, k] = fast_norm(w_2-w_1)
```

The issue here is, the hexagonal topology neighborhood seems weird, since it ignores some neighbors in the usual hexagonal topology. When run on the below example, a 3x3 hexagonal SOM, the middle neuron has all three bottom neurons assigned to its neighborhood. I hope the images elucidate it further.

## Example

```python
from minisom import MiniSom
import numpy as np

som = MiniSom(3, 3, 2, random_seed=1, topology="hexagonal")
som._weights = np.random.randint(1, 30, size=(3, 3))
som.distance_map()
```

Suppose that `som._weights` looks like the following:

```
[[15, 22, 29],
 [25, 24, 28],
 [21, 20,  7]]
```

After executing the code in the **Description** section, `um` looks like this:

```
[[[ 7. 10. nan nan nan nan nan nan]
  [ 6.  2.  3.  7. nan  7. nan nan]
  [nan  1.  7. nan nan nan nan nan]]

 [[ 1.  2. nan nan 10.  3. nan nan]
  [17.  4.  3.  1.  2.  4. nan nan]
  [nan 21.  4.  6.  1. nan nan nan]]

 [[ 2. nan nan nan  2.  1. nan nan]
  [nan nan nan  2.  1. 18. nan nan]
  [nan nan 18. 17. 21. nan nan nan]]]
```

See how `um[1, 1]` says that the middle neuron, with a hexagonal topology, borders all three 3rd row neurons: 17, 4, 3, which are the respective distances of 24 from 7, 20 and 21.

I don't think this should be happening. A hexagonal topology like the one below should imply the impossibility for the middle neuron to border all 3 neurons of either the top or bottom row.

![image](https://github.com/JustGlowing/minisom/assets/50002503/d6b70438-18b3-42ee-a807-add9f759eaa5)

## Version information

* `python 3.11.3`
* `numpy 1.24.3`
* `minison 2.3.1`

## Other

I think this is an easy fix (if it is indeed a bug, and not a misunderstanding), and I may open a PR for it if the maintainers ask me so.

I'm actually writing a paper on cluster analysis that uses `minisom` as the implementation for the SOM ANN, among other methods.

Thanks.

**Comment by JustGlowing** [comment]
hi @Pedro-V thanks for raising this.

I'm struggling to understand you point. Looking at the vector in `um` that you are referring to:

```
[17.  4.  3.  1.  2.  4. nan nan]
```

The middle weight in your snippet is considered to have 6 neighbors. Which can be seen as the ones highlighted here in red:

![image](https://github.com/JustGlowing/minisom/assets/4929177/0c3fb734-be11-4a90-b388-a65afe8fd8fb)

Please clarify your point if this doesn't clear your doubts.

**Comment by Pedro-V** [comment]
Hi @JustGlowing thanks for taking the time.

The thing is, the ones highlighted in red are not the ones that the `um` says the middle neuron is bordering! This is the problem I noticed.

The following is a mapping between each neighbor of the middle neuron (the red ones in your adapted image) and its distance to it. * denotes a neuron whose distance is present in `um[1, 1]`.
```
22 - 2 * 
29 - 5
28 - 4 *
7  - 17 *
20 - 4 *
25 - 1 *
```

See how the neuron with 29 value don't has his distance in `um[1,1]`? 
That's the reason I raised the issue. Why is 29 not present in the the middle neuron neighborhood? Indeed, executing the code of the method in a debugger shows it is not considered in the neighborhood of the middle neuron.

If this is a misunderstood, I'm sorry for taking your time 😆

**Comment by Pedro-V** [comment]
> We could have excluded any other 2 elements by rearranging the coordinates system.

I see. I thought that the coordinate was arranged in a way such that the array would be like the following

```
15   22   29
  25   24   28
21   20   7
```

Such that the middle neuron (24) woul have his neighborhood as `25, 20, 7, 22, 29, 28`, because that would make sense "visually". 

Again, thanks for taking the time. I'll close this issue.

**Comment by Pedro-V** [comment]
Hello @JustGlowing, I'm reopening this because of further doubt.

Again, suppose the same ` ii, jj` lists for helping define the neighborhood of the neuron. Also suppose the following code:

```python
ii = [[-1,  0, 0,  1, 1, 1], [-1, -1, -1,  0, 0, 1]]
jj = [[ 0, -1, 1, -1, 0, 1], [-1,  0,  1, -1, 1, 0]]

n, m = 3, 3

for x in range(n):
    for y in range(m):
        print(f'For {x, y}: ', end=' ')
        e = y % 2 == 0
        for k, (i, j) in enumerate(zip(ii[e], jj[e])):
            if (x + i >= 0 and x + i < n and
                y + j >= 0 and y + j < m):
                print(f'{x+i, y+j}', end=' ')
        print()
```

It outputs the following:

```
For (0, 0):  (0, 1) (1, 0) 
For (0, 1):  (0, 0) (0, 2) (1, 0) (1, 1) (1, 2) 
For (0, 2):  (0, 1) (1, 2) 
For (1, 0):  (0, 0) (0, 1) (1, 1) (2, 0) 
For (1, 1):  (0, 1) (1, 0) (1, 2) (2, 0) (2, 1) (2, 2) 
For (1, 2):  (0, 1) (0, 2) (1, 1) (2, 2) 
For (2, 0):  (1, 0) (1, 1) (2, 1) 
For (2, 1):  (1, 1) (2, 0) (2, 2) 
For (2, 2):  (1, 1) (1, 2) (2, 1) 
```

Consider the same map graph:

![](https://user-images.githubusercontent.com/4929177/238247088-0c3fb734-be11-4a90-b388-a65afe8fd8fb.png)

Now take the neuron (1, 0). In the above image, it has 5 neighbors:
``
 (0, 0)      (0, 1)
        (1, 0)       (1, 1)
(2, 0)       (2, 1)
```

My question why the code used in the `MiniSom.distance_map` method considers only 4 of its neighbors. 

Thanks.

**Comment by Pedro-V** [comment]
After working out in a paper sheet, I now understand. I misunderstood `minisom` concept of a hexagonal grid. Visually, `minisom` sees a hexagonal 3x3 grid like this:
```
 2
1 3
 5
4 6
 8
7 9
```

I was thinking it saw like this:

```
1 2 3
 4 5 6
7 8 9
```

Again, closing this issue. But definitely this time.
