### ISSUE TITLE
Order of Winning Coordinates

### ISSUE THREAD

**Issue by HAShihab** [JustGlowing/minisom#169]
Hi,

Thank you for sharing this amazing work!

I would like to confirm my understanding on the order of the coordinates being returned from the winner function.  

I see that the winner function uses numpy.unravel_index under the hood but does not explicitly pass in an "order" argument.  As per my understanding, this defaults to row-major so the output of winner should be in the form (row_id, col_idx).  However, when using some dummy data and following the Clustering Notebook example, the output from both winner and numpy.ravel_multi_index seem to be in column-major format?

**Comment by JustGlowing** [comment]
hi @HAShihab, the order of the coordinates is row, columns as per the unravel_index documentation.
