### ISSUE TITLE
hand written digits data set 

### ISSUE THREAD

**Issue by nishaa113** [JustGlowing/minisom#17]
i'm trying to use my own set of images for this example but it keeps giving me the following error when training:
non-broadcastable output operand with shape (64,) doesn't match the broadcast shape (1,64)

i have tried reshaping each image to a vector and appending it to the data array. i'm quite lost with this and haven't been able to find much of a solution for it.

**Comment by JustGlowing** [comment]
hi @nishaa113 try reshaping forcing the shape to (1,64). For example: `your_images.reshape(1, 46)`

**Comment by nishaa113** [comment]
oh thanks!
that solved this issue. can you also help me as to how we can arrange the target array to get the plot?

**Comment by nishaa113** [comment]
ok thanks!!
also, i need to find out which of the nodes are activated and print it as output.
so i have trained a 1x3 som, and i need to print in array the node that has been activated for an input after i have trained the som.
the output will be in the form of [1,0,0] or [0,1,0] or [0,0,1]

can you help me as to how i can get this?

**Comment by JustGlowing** [comment]
I'm not sure I understand what you want to do. Please check the examples here:

https://github.com/JustGlowing/minisom/blob/master/examples/examples.ipynb

**Comment by nishaa113** [comment]
i did see the examples but i couldn't find much help there.
i simply want to print which number node is the winner for any input to the trained som.

**Comment by JustGlowing** [comment]
Then you just have to use this method:

https://github.com/JustGlowing/minisom/blob/master/minisom.py#L132

**Comment by nishaa113** [comment]
and is there any way to save the trained som and just load it later?

**Comment by JustGlowing** [comment]
MiniSom has the attribute weights, it's a numpy matrix that can be save with the function numpy.save. If you want to reuse a MiniSom, you can crate an instance, train and save the weights. When you want to reuse that network, you can create a new instance, load the weights from a file and overwrite the attribute weights.

**Comment by nishaa113** [comment]
can i get the instruction for getting the weights as well as loading them?

because i just tried and it gave me the error:
"'MiniSom' object has no attribute 'weights'"

**Comment by JustGlowing** [comment]
You have to put an underscore: `_weights`.

The attribute is initialized here: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L82
