### ISSUE TITLE
How to save and load trained model for cluster prediction on new data?

### ISSUE THREAD

**Issue by mushtaqpatel0505** [JustGlowing/minisom#170]
How to save and load trained model for cluster prediction on new data?

**Comment by JustGlowing** [comment]
- This example shows how to save and load models: https://github.com/JustGlowing/minisom#export-a-som-and-load-it-again
- This example shows how to perform clustering: https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb
