### ISSUE TITLE
PCA initialization 

### ISSUE THREAD

**Issue by emeeubc** [JustGlowing/minisom#171]
The eigenvectors used in PCA initialization seem off to me. I've tried to explain using the "Sales_Transactions_Dataset_Weekly.csv" dataset from the time series example. This dataset has 811 variables (different products), each with a time series of 52 observations (52 weeks). 

        pc_length, pc = linalg.eig(cov(transpose(data)))

^This line in minisom calculates a covariance matrix of (52, 52) and eigenvectors of (52, 52) for PCA initialization. However, we are trying to compare 811 different time series, so don't we want a covariance matrix of (811, 811) and eigenvectors of (811, 811)?

I wonder if the PCA initialization should be as follows: 

        pc_length, eigvecs = linalg.eig(cov(data))      
        pc = (eigvecs.T @ data)                                 
        pc_order = argsort(-pc_length)
        for i, c1 in enumerate(linspace(-1, 1, len(self._neigx))):
            for j, c2 in enumerate(linspace(-1, 1, len(self._neigy))):
                self._weights[i, j] = c1*pc[pc_order[0]] + \                  
                                      c2*pc[pc_order[1]]

The first line calculates eigenvectors with a length of 811. The second line calculates principal components with a length of 52 in the direction of the eigenvectors. These eigenvectors and principal components are the same as the scikit-learn PCA implementation. 

Thanks in advance!

**Comment by JustGlowing** [comment]
I'll look into this asap, in the meanwhile please refer to this conversation https://github.com/JustGlowing/minisom/issues/147

**Comment by emeeubc** [comment]
Thank you very much for looking into this. I have read conversation #147 and that change to indexing with pc[:,pc_order[0]] makes sense for column-wise eigenvectors. In the snippet of code above, I use pc[pc_order[0]] for indexing because the principal components (pc) are row-wise.

**Comment by JustGlowing** [comment]
Thanks for this @emeeubc  I had a look at you suggestion and your snippet of code is correct. Would you be happy to raise a pull request with the suggested changes?

**Comment by emeeubc** [comment]
Yes no problem, I've made the pull request. Please let me know if there are any issues. Thanks for your quick response!

**Comment by racng** [comment]
Can there be an option to use the previous PCA calculation? I have data where the number of rows is much greater than the number of columns. The new PCA calculation is very slow for my data since dimension of cov(data) is very large.

**Comment by JustGlowing** [comment]
@racng see here https://github.com/racng/minisom/commit/618eb5e6095394d5926c0b7a0ed69d2476837bbd#commitcomment-139246212
