### ISSUE TITLE
Adjacent nodes in hexagonal distance do not have distance 1

### ISSUE THREAD

**Issue by aznt00th** [JustGlowing/minisom#173]
Due to the shifting of 0.5 of x axis and the lack of shifting of y axis, nodes are closer to their adjacent x-axis neighbours than they are their diagonal neighbours. This could be resolved by adding a shifting factor of sqrt(3)/2 to the y axis and adjusting the _topographic_error_hexagonal to calculate neighbours based on distance of 1 between vectors. However, the current tests for topographic error simply set the topology to hexagonal/rectangular without re-initialising, so using the new topographic error will cause that test to fail.

**Comment by aznt00th** [comment]
I have some code ready to submit (with the failing test) but figure that before I go about changing that test, I should verify my understanding

**Comment by JustGlowing** [comment]
hi @aznt00th thanks for pointing this out. Please propose your changes with a pull request and I'll evaluate them.
