### ISSUE TITLE
unexpected problem calling the functions

### ISSUE THREAD

**Issue by tomaszek0** [JustGlowing/minisom#179]
The functions currently cause errors when called:
AttributeError: 'MiniSom' object has no attribute 'get_weights'
### basicusage.ipnyb
MiniSom
TypeError: MiniSom.__init__() got an unexpected keyword argument 'neighborhood_function' # ok after deleting
TypeError: MiniSom.__init__() got an unexpected keyword argument 'topology' # ok after deleting
som.pca_weights_init()
AttributeError: 'MiniSom' object has no attribute 'pca_weights_init' # ok after fixing to: som.random_weights_init()
som.train()
AttributeError: 'MiniSom' object has no attribute 'train' # ok, after fixing to: som.train_random
TypeError: MiniSom.train_random() got an unexpected keyword argument 'verbose' # ok, after deleting
som.topographic_error()
AttributeError: 'MiniSom' object has no attribute 'topographic_error'

and so on
--> MiniSom Version: 2.3.1 / Win10

**Comment by JustGlowing** [comment]
hi there, I'm afraid I can't replicate your errors. Make sure you're using Python3 and that MiniSom is installed correctly on your machine.

**Comment by tomaszek0** [comment]
Hi, I updated my conda packages, and here's what I did:
Python 3.11.5 (conda 23.9.0)  updated to Python 3.11.7 (conda 23.11.0)
numpy 1.24.3 upgraded to 1.26.3
pandas 2.0.3 upgraded to 2.1.4
matplotlib 3.7.2 upgraded to 3.8.2
scikit-learn 1.3.2

But these changes didn't result in the problem disappearing. 
The attribute errors are still being generated:
'MiniSom' object has no attribute 'get_weights'
'MiniSom' object has no attribute 'labels_map'
'MiniSom' object has no attribute 'topographic_error_rectangular'

Since the MiniSom did not have large code snippets, I copied minisom.py directly to my Jupyter notebook. and deactivated entry "#from minisom import MiniSom". As a result, this fixes the problem, and the Attribute error 'MiniSom' object has no attribute 'get_weights' does not appear.

**Comment by JustGlowing** [comment]
it looks like you're importing something wrong. Have you reting installing minisom using pip?

**Comment by tomaszek0** [comment]
The Attribution Errors were generated when executing the code importing the MiniSom library, i.e. after installing the MiniSom using pip. The pasted code from the minisom.py was used to bypass the problems and it worked fine.
Thus, today, I uninstalled minisom: pip uninstall minisom
and then I installed it again:  pip install minisom
pip show minisom

Unfortunately, executing the code generates an error:AttributeError: 'MiniSom' object has no attribute 'get_weights'

**Comment by JustGlowing** [comment]
I tried to replicate your issue by installing minisom via pip in a fresh Python 3.11 environment but everything worked as expected. I suggest the following actions:

1. Create a clean virtual environment `virtualenv <your_dir_of_choice>`
2. Activate it `source <your_dir_of_choice>/bin/activate`
3. Install numpy and minisom in the environment `pip install numpy minisom`
4. Try to run your code

**Comment by tomaszek0** [comment]
Unfortunately, applying the 'som' code in the new environment failed to alter the situation.
I followed the steps below:
conda create --name som_env # to create the virtual environment.
conda activate som_env
"pip install packages"
Start Jupyter Notebook from within a new conda environment
!conda info # check env -> ok 'som_env'
Run code.

AttributeError: 'MiniSom' object has no attribute 'get_weights'

Additionally, I noticed that the generated U-matrix is not the same in both situations, i.e. the pasted minisom.py code generates a different pattern than the result obtained from the imported MiniSom function.

**Comment by JustGlowing** [comment]
Do not install anything else apart from numpy and minisom in the new environment. Run a simple code snippet from the python terminal to test that minisom is working:

```
from minisom import MiniSom
som = MiniSom(2, 2, 3)
som. get_weights()
```

**Comment by tomaszek0** [comment]
So, I removed the existing environment and created a new one.  The installation of 'numpy' using pip displayed the message 'Requirement already satisfied'. I got this done by running the "conda install numpy" and 'pip install minisom. This time, both installations were successful.

> conda activate som_env
(som_env)> jupyter notebook
in jupyter:
# check env
!conda info 
# ok som_env

from minisom import MiniSom
som = MiniSom(2, 2, 3)
som.get_weights()
AttributeError: 'MiniSom' object has no attribute 'get_weights'
dir(som)
['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activate',
 '_decay_function',
 '_init_T',
 'activate',
 'activation_map',
 'activation_response',
 'diff_gaussian',
 'distance_map',
 'gaussian',
 'learning_rate',
 'neighborhood',
 'neigx',
 'neigy',
 'quantization',
 'quantization_error',
 'random_generator',
 'random_weights_init',
 'sigma',
 'train_batch',
 'train_random',
 'update',
 'weights',
 'win_map',
 'winner']

**Comment by JustGlowing** [comment]
The fact that you got a "Requirement already satisfied" means that the environment already had libraries installed. Please use virtualenv as suggested above rather than conda.

Also, check that you are actually using the python from the virtual environment by using:
```
import sys
print(sys.executable)
```
also check that the minisom you import is where you expect it to be:
```
import minisom
print(minisom.__file__)
```

**Comment by tomaszek0** [comment]
I removed existing som_env (conda remove --name som_env –all) and then created virtual env using virtualenv. Now, there is no message "Requirement ..." and packages have been installed. 
Testing:
from minisom import MiniSom
som = MiniSom(2, 2, 3)
som.get_weights()
Result: an array
import sys
print(sys.executable)
Result: ...\anaconda3\python.exe
import minisom
print(minisom.__file__)
Result:  \anaconda3\Lib\site-packages\minisom.py

and my code works properly.

**Comment by JustGlowing** [comment]
Great! You can keep using that environment. Not sure what's the problem with conda.
