### ISSUE TITLE
errors in 'AdvancedVisualization.ipnyb' example

### ISSUE THREAD

**Issue by tomaszek0** [JustGlowing/minisom#180]
Great job with the example, but I encountered some errors and couldn't see the visualization. Here are the issues:

**The property plot section**
>TypeError 
Cell In[6], line 52
---> 52 showPropertyPlot(som, data, columns[:-1])
Cell In[6], line 27, in showPropertyPlot(som, data, columns)
---> 27 zmin=min(np.min(properties.iloc[:,2:]))
TypeError: 'float' object is not iterable

**def plotDistributionOfDataInClusters section**
> AttributeError 
~\AppData\Local\Temp\ipykernel_17916\102937540.py in ?()
     30     minimum=min([l.min() for l in distributionMapData['min'].values])
     31 
     32     distributionMap(distributionMapData, clusters, size, columns, minimum, maximum, plottype)
     33 
---> 34 plotDistributionOfDataInClusters(som, data, columns[:-1], plottype='barpolar')
~\AppData\Local\Temp\ipykernel_17916\102937540.py in ?(som, data, columns, plottype)
     12         means=np.mean(winner, axis=0)
     13         maxima=np.max(winner, axis=0)
     14         row=int(position[1]+1)
     15         col=int(position[0]+1)
---> 16         distributionMapData=distributionMapData.append(
     17             {'col': col,
     18              # row needs to be shifted because all the other plots (heatmaps) are shown with row 0 at bottom
     19              'row': size-row+1,
~\AppData\Roaming\Python\Python311\site-packages\pandas\core\generic.py in ?(self, name)
   6200             and name not in self._accessors
   6201             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   6202         ):
   6203             return self[name]
-> 6204         return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'

**def plotStarburstMap(som) section**
>AxisError
Cell In[11], line 34
     29     fig.update_layout(shapes=shapes.tolist(), 
     30         width=500,
     31         height=500) 
     32     fig.show()
---> 34 plotStarburstMap(som)
Cell In[11], line 15, in plotStarburstMap(som)
     13 for row in np.arange(som.distance_map().shape[0]):
     14     for col in np.arange(som.distance_map().shape[1]):
---> 15         cx,cy = findInternalNode(row, col, som.distance_map().T)
     16         shape=go.layout.Shape(
     17                 type="line",
     18                 x0=row,
   (...)
     25                 )
     26             )
     27         shapes=np.append(shapes, shape)
Cell In[9], line 10, in findInternalNode(x, y, umat)
      9 def findInternalNode(x, y, umat):
---> 10     minx, miny = findMin(x,y,umat)
     11     if (minx == x and miny == y):
     12         cx = minx
Cell In[9], line 4, in findMin(x, y, umat)
      2 newxmin=max(0,x-1)
      3 newxmax=min(umat.shape[0],x+2)
----> 4 newymin=max(0,y-1)
      5 newymax=min(umat.shape[1],y+2)
      6 minx, miny = np.where(umat[newxmin:newxmax,newymin:newymax] == umat[newxmin:newxmax,newymin:newymax].min())
File ~\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:2810, in max(a, axis, out, keepdims, initial, where)
   2692 @array_function_dispatch(_max_dispatcher)
   2693 @set_module('numpy')
   2694 def max(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,
   2695          where=np._NoValue):
   2696     """
   2697     Return the maximum of an array or maximum along an axis.
   2698 
   (...)
   2808     5
   2809     """
-> 2810     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2811                           keepdims=keepdims, initial=initial, where=where)
File ~\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:88, in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85         else:
     86             return reduction(axis=axis, out=out, **passkwargs)
---> 88 return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
AxisError: axis 1 is out of bounds for array of dimension 0

**Comment by JustGlowing** [comment]
hi, thanks for raising this issue. I don't have capacity to maintain this notebook and it will soon be removed. Feel free to submit a PR with the changes if you solve the issues.

**Comment by tomaszek0** [comment]
ok, moje niedopatrzenie- sprawdziłem jeszcze raz. Jednak wciąż pozostają 2 błędy:
The property plot : Type error: 'float' object is not iterable
Ten błąd naprawiłem poprzez:
zmin = min(properties.iloc[:,2:].min())
zmax = max(properties.iloc[:,2:].max())

def plotDistributionOfDataInClusters: AttributeError: 'DataFrame' object has no attribute 'append'
