### ISSUE TITLE
Help with clustering and visualization of neurons 

### ISSUE THREAD

**Issue by zmajstorovic** [JustGlowing/minisom#182]
Hi, I'm reaching to you hoping that you can help me. 

This is the snippet of my input `data` and `som` settings: 
`data= [[0.0, 0.85, 0.0, 0.0, 0.0, 0.85, 0.0, 0.85], [0.0, 0.85, 0.0, 0.9, 0.0, 0.85, 0.0, 0.9]...]`
`som = MiniSom(4, 4, 8, learning_rate= 0.5, neighborhood_function='gaussian', sigma=1.0)`

I followed your tutorial on clustering, and instead of getting neuron-cluster representation I get neurons plotted in sets of four of the same color (total 16 neurons). I expected 16 different colors, each color for one set of the data assigned to certain neuron.   
For image plotting I used the same code as in [Clustering notebook](https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb)

![image_2024-02-20_143623737](https://github.com/JustGlowing/minisom/assets/18489380/a72eaf05-4dad-45e2-914a-d063de3a4c11)

`som.winner(data[0])` gets me the result e.g. `(3,1)`

With `som.get_weights()` I have following values: 
![image](https://github.com/JustGlowing/minisom/assets/18489380/0b6205e9-c9f6-4bb4-bfa9-7b91c189bcd1)

**Question**: How do I get neuron coordinates from this table? I don't understand how `(3,1)` translates to coordinate system same as the input data.

**Comment by JustGlowing** [comment]
hi,

> I followed your tutorial on clustering, and instead of getting neuron-cluster representation I get neurons plotted in sets of four of the same color (total 16 neurons). I expected 16 different colors, each color for one set of the data assigned to certain neuron.

Even if you have 16 neurons, during clustering only a subset might end up mapping some samples. 

> Question: How do I get neuron coordinates from this table? I don't understand how (3,1) translates to coordinate system same as the input data.

- You can use the method `winner` to get neuron coordinates.
- `(3, 1)` is used to define the size of the map.

My advice is to use a map with a small number of neuron first (for example `(3,1)`) and see if the results look like in the example, if so you can start increasing the size until it makes sense for you.
