### ISSUE TITLE
There might be an index error in TimeSeries.ipynb

### ISSUE THREAD

**Issue by xjxj0322** [JustGlowing/minisom#183]
Thanks a lot for creating and maintaining the minisom package! It helps me a lot in my study and research.
When I was having a try of TimeSeries.ipynb, I found that there might be an index error:

> plt.subplot(the_grid[6-position[1], position[0]])

It makes the first row of subplots to appear in the last row.

The quoted line should be corrected to:

> plt.subplot(the_grid[7-position[1], position[0]])

Or using:

> plt.subplot(8, 8, 8*(8-position[1]-1)+(position[0]+1))

Below is the correct plot.

![time_series2](https://github.com/JustGlowing/minisom/assets/70789910/0054f11d-dbb1-49fe-b311-7c57648c326b)

**Comment by JustGlowing** [comment]
Very well spotted! I Just pushed the changes you suggested.
