### ISSUE TITLE
ModuleNotFoundError: No module named 'minisom'

### ISSUE THREAD

**Issue by AkinaMH** [JustGlowing/minisom#193]
### Describe the bug
Traceback (most recent call last):
  File "E:\PyCharm\G-SOMO\Test.py", line 17, in <module>
    from minisom import MiniSom
ModuleNotFoundError: No module named 'minisom'

But I already have MiniSom==2.3.3 installed in my environment!

**Comment by JustGlowing** [comment]
Make sure that you installed minisom in the environment where you're running you script. My suggestion is to use a virtual environment: https://virtualenv.pypa.io/en/latest/user_guide.html.

**Comment by AkinaMH** [comment]
Yeah, I've done what you said about creating a new virtual environment and installing MiniSom, but it still reports an error.

**Comment by JustGlowing** [comment]
In your script run 

```

**Comment by JustGlowing** [comment]
run this in your script:

```
>>> import sys
>>> print(sys.executable)
```

If the result is what you expect, make sure that the pip you are using belongs to the virtual environment.

**Comment by AkinaMH** [comment]
PyCharm's terminal already shows that the Mini environment is activated (Mini is the name of my virtual environment), but executing the Test.py file in PyCharm import sys
and print(sys.executable) code in PyCharm, it does not show that the Mini environment is entered.

---------------------------------------
This is the message to switch into the virtual environment (Mini).

(.venv) PS E:\PyCharm\G-SOMO> .\Mini\Scripts\activate
(Mini) PS E:\PyCharm\G-SOMO> 

--------------------------------------------------
This is what the Test.py file in PyCharm shows after executing the code you described.

E:\PyCharm\G-SOMO\.venv\Scripts\python.exe

**Comment by AkinaMH** [comment]
(.venv) PS E:\PyCharm\G-SOMO> .\Mini\Scripts\activate
(Mini) PS E:\PyCharm\G-SOMO> python Test.py    
Traceback (most recent call last):
  File "E:\PyCharm\G-SOMO\Test.py", line 18, in <module>
    from minisom import MiniSom
ModuleNotFoundError: No module named 'minisom'
(Mini) PS E:\PyCharm\G-SOMO>

----------------------------------------------------------

This is the error I get from executing my Test.py file in a virtual environment.
Here is the content of Test.py:

data = [[ 0.80,  0.55,  0.22,  0.03],
        [ 0.82,  0.50,  0.23,  0.03],
        [ 0.80,  0.54,  0.22,  0.03],
        [ 0.80,  0.53,  0.26,  0.03],
        [ 0.79,  0.56,  0.22,  0.03],
        [ 0.75,  0.60,  0.25,  0.03],
        [ 0.77,  0.59,  0.22,  0.03]]

from minisom import MiniSom
som = MiniSom(6, 6, 4, sigma=0.3, learning_rate=0.5)
som.train(data, 100)

**Comment by AkinaMH** [comment]
My computer environment is Windows 11 and MiniSom==2.3.3.

**Comment by JustGlowing** [comment]
This python executable that you are using does not belong to virtual environment that you are using.

You are using `E:\PyCharm\G-SOMO.venv\Scripts\python.exe`

While you virtual environment is in `E:\PyCharm\G-SOMO\Mini`

I might be wrong as I'm not familiar with your operating system. You can use `pip freeze` to check which packages are installed. Again, make sure to use the pip associate with the python version that you want to use.
