### ISSUE TITLE
Class assigment in an unspervised task

### ISSUE THREAD

**Issue by LangLEvoI** [JustGlowing/minisom#194]
Hi there. Thanks for open-sourcing this tiny but powerful tool. I’m unfamiliar with SOM and wonder if it is possible to get the probability that a neuron belongs to a certain class in an unsupervised task.

An [example](https://github.com/JustGlowing/minisom/blob/master/examples/BasicUsage.ipynb) of the class assignment in a supervised task was given. If I understand correctly, the pie chart with mixed colours here actually represents probabilities that a neuron at the fuzzy boundary would be classified into more than one class. The single colour means it 100% belongs to one certain class.

Say, my 2-D data (class A and class B) is as follows,

```python
data = [[12.6, 4.3], [8.6, 2.3]]
```

After training, assuming there are 9x9 neurons, a boundary may divide the neurons into two classes. When I have a value to be predicted, say, `[13.6, 5 8]`, `som.winner([13.6, 5.8])` can get the winning neuron. My question is, can I get probabilities of the winning neuron to two classes, as above example did?

**Comment by JustGlowing** [comment]
hi @LangLEvoI , please check this other example https://github.com/JustGlowing/minisom/blob/master/examples/Classification.ipynb

**Comment by LangLEvoI** [comment]
Thank you for your reply!

Within both examples, the method is the key, linking neurons and classes using labelled samples. But if I don't have labelled samples, that is, in a clustering task, how can I know the class assignment for each neuron?

I'm not sure if the distance between neurons can be as the probability of class assignment?

```python
s_pos = som.get_weights()[som.winner(S)]  # get the BMU of S (the sample to be classified)
dist_matrix = som.activate(s_pos)  # get the activation map to the BMU of S
dist_a = dist_matrix[som.winner(A)]  # distance between BMU of S and class A
dist_b = dist_matrix[som.winner(B)]  # distance between BMU of S and class B
prob_a = (1/dist_a) / (1/dist_a+1/dist_b)
prob_b = (1/dist_b) / (1/dist_a+1/dist_b)
```

**Comment by JustGlowing** [comment]
If you don't have class labels, it's a clustering task indeed and you can look at this example on how to assign the cluster label: https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

You can try to use the distance between neurons as probabilities but it might not always work.
