### ISSUE TITLE
Clarification on behavior of activations per class

### ISSUE THREAD

**Issue by SeanPedersen** [JustGlowing/minisom#196]
Hey,
great package - had some fun playing around with it already. I noticed that the SOM always produces a corner that has low similarity for all data points, is this intended / explainable behavior?

Here is an image of avg activation for the grid for CIFAR-10 CLIP embeddings:
![avg-actis-som-cifar10](https://github.com/user-attachments/assets/d345c19f-dc2a-4e6b-854c-cae46c5db03a)

For every class the top right corner has high distances - this seems strange to me. I observed the same for both triangle and gaussian neighborhood_function parameter.

Here my training code:
```
grid_x, grid_y = 16, 16
som = MiniSom(grid_x, grid_y, embeddings.shape[1], sigma=4,
              learning_rate=0.5, neighborhood_function='gaussian') # triangle
som.pca_weights_init(embeddings)
som.train(embeddings, 8000, random_order=True, verbose=True)
```

**Comment by JustGlowing** [comment]
Hi, this might be due to initialization method that you are using. Instead of `pca_weights_init`, try `random_weights_init` or don't attempt to initialize the weights (they're randomly initialized by default).

**Comment by JustGlowing** [comment]
Try reducing sigma to 1 or using a different neighborhood function with a small value fo sigma.

**Comment by JustGlowing** [comment]
Weird things can happen at the border as that they have less neighbors, but your results are due to your specific situation.

I've replicated your code on a different problem and had the following result:

![image](https://github.com/user-attachments/assets/8fd7ece4-becf-45cb-950c-99532ab97409)

Here's the code I used:

```
from minisom import MiniSom

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

columns=['area', 'perimeter', 'compactness', 'length_kernel', 'width_kernel',
                   'asymmetry_coefficient', 'length_kernel_groove', 'target']
data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt', 
                    names=columns, 
                   sep='\t+', engine='python')
target = data['target'].values
label_names = {1:'Kama', 2:'Rosa', 3:'Canadian'}
data = data[data.columns[:-1]]
# data normalization
data = (data - np.mean(data, axis=0)) / np.std(data, axis=0)
data = data.values

# Initialization and training
n_neurons = 29
m_neurons = 29
som = MiniSom(n_neurons, m_neurons, data.shape[1], sigma=3, learning_rate=.5, 
              neighborhood_function='triangle', random_seed=0, topology='rectangular')

#som.pca_weights_init(data)
som.random_weights_init(data)
som.train(data, 5000, verbose=False)  # random training

num_classes = 3
#fig, axes = plt.subplots(1, 3, figsize=(15, 6)) # Adjust figsize as needed
#axes = axes.ravel()  # Flatten the axes array
plt.figure()
for t in np.unique(target):
    activations = [som.activate(x) for x in data[target==t]]
    plt.subplot(2, 2, t)
    plt.imshow(np.mean(activations, axis=0), cmap='hot')
    plt.colorbar(im, ax=axes.ravel().tolist()) # Add colorbar for all subplots

# Adjust layout to prevent overlapping titles
plt.tight_layout()
plt.colorbar() 
plt.show()
```

If you're not happy with your results, try changing the grid size, sigma and favor neighborhood functions that are not smooth like triangle and bubble.

**Comment by JustGlowing** [comment]
You're welcome, the parameters are described in the doc string of the constructor: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L82

**Comment by JustGlowing** [comment]
Please keep in mind that the parameters I used will not give you better results in terms of clustering or classification. They only avoid the artifact that you mentioned.
