### ISSUE TITLE
example_digits.py uses deprecated feature in Matplotlib

### ISSUE THREAD

**Issue by harriv** [JustGlowing/minisom#2]
When running example_digits.py following warning is printed on console:

    Warning (from warnings module):
      File "C:\Python34\lib\site-packages\matplotlib\axes\_subplots.py", line 69
        mplDeprecation)
    MatplotlibDeprecationWarning: The use of 0 (which ends up being the _last_ sub-plot) is deprecated in 1.4 and will raise an error in 1.5

**Comment by JustGlowing** [comment]
I don't get warning. Probably you're using a newer version of matplotlib. (I have 1.3.1)

**Comment by harriv** [comment]
Yes, I've version 1.4, and version 1.5 will raise an error as the warning message states.

**Comment by JustGlowing** [comment]
Thanks for reporting.
