### ISSUE TITLE
Why we need to normalize all the weights?

### ISSUE THREAD

**Issue by jeffchy** [JustGlowing/minisom#20]
Hi, wonderful code, but I'm wondering why we have to normalize the weights all the time?
https://stackoverflow.com/questions/13687256/is-it-right-to-normalize-data-and-or-weight-vectors-in-a-som
I think it will be cool if we can decide whether to perform weights normalizing.

**Comment by JustGlowing** [comment]
hi! Thanks for writing. Not sure there's an elegant way to provide this option but I'll see what I can do.

**Comment by JustGlowing** [comment]
After thinking about this issue for a while I decided to remove the normalization step from the update method.

Reasons: 
- The user can now use the weights of the trained som directly as quantized versions of the data in input.
- This way the user is not forced to normalize the data in input to achieve good results.

**Comment by lakesare** [comment]
My textbook (published in 2009) advises normalizing (and by normalization here we mean making the vector have length 1) the weights on each `def update` in 4) iii).

<img width="514" alt="image" src="https://user-images.githubusercontent.com/7578559/153772216-9d154a34-340f-46dc-9525-fd60b27227cc.png">

Do you think this is not a standard algorithm, or maybe is "length 1" not a standard normalization technique? I'll override the update method on my own if I need to, but I wonder what you think of the overall picture.

**Comment by JustGlowing** [comment]
The book presents a sensible way to train a som but assumes a specific way to normalize the data (dividing by the norm). My suggestion would be to normalize your data in a way that makes sense to your problem, then try minisom as it is now. You can normalize the weights in case the results are not what you expect.
