### ISSUE TITLE
Train progress output

### ISSUE THREAD

**Issue by JanVargovsky** [JustGlowing/minisom#22]
Is it possible to add progress support for `train_batch(...)` and `train_random(...)` methods? For instance using the tqdm library?

**Comment by JustGlowing** [comment]
Hi, this has been on my to-do list for quite a while but I struggle to implement it in an elegant way. Maybe I'll take some time during the holidays.

**Comment by JustGlowing** [comment]
If you look at https://github.com/JustGlowing/minisom/blob/master/examples/examples.ipynb there's an example that shows how to do it using the public methods.

**Comment by JanVargovsky** [comment]
I've seen the mentioned examples but it does not track internal progress. I've created a PR with this feature. Default behaviour is still the same.
