### ISSUE TITLE
DemocracyIndex example doesn't seem to work with current version of minisom. 

### ISSUE THREAD

**Issue by ZALaurens** [JustGlowing/minisom#24]
Hi,

1. To get the DemocracyIndex example working I had to drop the last row from democracy_index (democracy_index = democracy_index[:-1])  which is a repeat of the header row in the Wikipedia table

2. Minisom also didn't like neighborhood_function which I replaced with decay_function (hope that's the same). 

3. But now I get  
 File "C:mypath...\minisom2.py", line 221, in update
    eta = self._decay_function(self._learning_rate, t, max_iteration)
TypeError: 'str' object is not callable

when executing som.train_random(X, 1000)

Any advice?

**Comment by JustGlowing** [comment]
Hi @ZALaurens, Thanks for using MiniSom!

`decay_function` and `neighborhood_function` are not the same and it's better if you don't to swap them. If you had an error involving the  `neighborhood_function` please post it.

Make sure you have the latest version of minisom.

**Comment by ZALaurens** [comment]
Hi @JustGlowing ,

It seems I was using an older version of minisom which I downloaded from the DeepLearning from A to Z course on Udemy even though I had downloaded the one from Github. Now made sure to use this version and it all works! 

Minisom is a great piece of software and the DemocracyIndex is a nice example close to my own interests.

Laurens
