### ISSUE TITLE
How can I predict which cluster my input data belong to in a prediction phase?

### ISSUE THREAD

**Issue by GowthamyVaseekaran** [JustGlowing/minisom#25]
After training the SOM using minisom library, if this som model can predict a potential cluster from a new instance of data? Like for example, the trained SOM I have two clusters. Now am gonna do the prediction with new data instances. I need to output the cluster type of the new input data. Is there any  inbuilt methods available in the minisom to predict/output the cluster type?

**Comment by JustGlowing** [comment]
Hi @GowthamyVaseekaran, you can use the method `winner(x)`, it returns the coordinates of the winning neuron for the samples `x`.

**Comment by GowthamyVaseekaran** [comment]
@JustGlowing Thank you for your quick response. Can we get the cluster details? I mean which cluster that sample x belongs to?

**Comment by JustGlowing** [comment]
The cluster coordinates represent the cluster. Each neuron represents a cluster.

**Comment by GowthamyVaseekaran** [comment]
Thank you got it

**Comment by JustGlowing** [comment]
@GowthamyVaseekaran  Happy to help! Please leave a start if you like MiniSom ;-)
