### ISSUE TITLE
Is that posiible to predict the winner coordianates with two parameter values

### ISSUE THREAD

**Issue by ramibabu** [JustGlowing/minisom#27]
Please note the $subject.

Lets say I have two columns in my training dataset like x and y. I want to train the SOM with that two values.So AFAIK, Weight vectors should be the same length as the input vectors (in my case its two), which are dynamically updated based on the values of the measurement vectors in the training data. So each neurone's weight should have two values( for an instance: neurone in 0,1 co-ordinate will have weights as [x,y]). So during the training period,  each neurones in the som should be trained using those two vectors. So my question is, Is that possible to achieve this using miniSOM library? 

My next question is, If I can do the training using above mentioned method, during the prediction period, if I want to get the winner coordinate for the input sample data using **winner(x)** method can I pass two values? because I want to predict the winner node using two values as I mentioned earlier x and y

**Comment by JustGlowing** [comment]
hi @ramibabu the answer to both your questions is yes. You just have to arrange your data in a 2-by-N matrix.

Leave a star if you like MiniSom ;-)

**Comment by ramibabu** [comment]
If you don't mind, can you please guide me how can I arrange the data in a 2-by-N matrix?

**Comment by ramibabu** [comment]
Is there any specific function available?

**Comment by JustGlowing** [comment]
Here's an example of your data matrix can be:
```
data = [[.1, .3],
        [.4, .2],
        [.3, .2]]
```
