### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by xuezhaokun** [JustGlowing/minisom#29]
Hi, 
When I tried to import minisom, I got this syntax error:

> 
> from minisom import MiniSom
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/minisom.py", line 23
>     progress = f'\r [ {0:{len(str(m))}} / {m} ] {0:3.0f}% ? it/s'
>                                                                 ^
> SyntaxError: invalid syntax

I installed minisom via 'pip install minisom' and I am using Python 2.7.12.

Any idea?
Thanks!

**Comment by JustGlowing** [comment]
Hi @xuezhaokun , you need Python 3.

**Comment by xuezhaokun** [comment]
I see. Thanks!

**Comment by jacksgt** [comment]
I have the same error with Python 3.5:

```
$ python3 run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from minisom import MiniSom
  File "/home/henschjk/.local/lib/python3.5/site-packages/minisom.py", line 23
    progress = f'\r [ {0:{len(str(m))}} / {m} ] {0:3.0f}% ? it/s'
                                                                ^
SyntaxError: invalid syntax
```

**Comment by JustGlowing** [comment]
You need Python 3.6 as it supports f-strings.

**Comment by jacksgt** [comment]
Yes, I just saw it was introduced in [PEP 498](https://www.python.org/dev/peps/pep-0498/).

I think you should add that to the README.

Thank you for the super quick answer!
