### ISSUE TITLE
Installing minisom

### ISSUE THREAD

**Issue by Sarwat-Fatima** [JustGlowing/minisom#3]
If I try to setup.py file, it gives me the following error

warnings.warn(msg)
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

Can you please guide me how to install your package?

**Comment by JustGlowing** [comment]
Hi Sarwat, did you run the following command?
```
python setup.py install
```

**Comment by Sarwat-Fatima** [comment]
No, I read it but I could not figure out where I have to run this command. Is it on the console or on cmd. I ran a few example codes of yours for the iris data. They ran perfectly even though I didn't run any install command.

**Comment by JustGlowing** [comment]
On the command line of your operating system. You may want to give a look at this probably:

https://pythonhosted.org/an_example_pypi_project/setuptools.html
