### ISSUE TITLE
What is the algorithm minisom uses to find the Best matching Neuron (Unit) ?  

### ISSUE THREAD

**Issue by GowthamyVaseekaran** [JustGlowing/minisom#31]
Please note $subject. Can u please briefly explain it

**Comment by JustGlowing** [comment]
Hi @GowthamyVaseekaran, the best matching neuron for a sample `x` is the neuron such that `||x-w||`is minimum where `w` are the weights of the neuron.

**Comment by GowthamyVaseekaran** [comment]
@JustGlowing Thank you.

 I have another small doubt. Is there any way to save the model after the training for the future prediction? Or else do we need to train again and again for each run?

**Comment by JustGlowing** [comment]
You can check out the documentation for this: https://github.com/JustGlowing/minisom#export-a-som-and-load-it-again

**Comment by GowthamyVaseekaran** [comment]
> Hi @GowthamyVaseekaran, the best matching neuron for a sample `x` is the neuron such that `||x-w||`is minimum where `w` are the weights of the neuron.

In my opinion, Instead of `||x-w||`, comparing the Euclidean distance of the input measurement vector to each neuron’s weight in the map will give more accurate results. What is your opinion on that sir?

**Comment by JustGlowing** [comment]
hi again @GowthamyVaseekaran, `||x-w||` is the norm of `x-w` and it corresponds to the euclidean distance. Have a look here: https://en.wikipedia.org/wiki/Euclidean_distance

**Comment by GowthamyVaseekaran** [comment]
Thank you for the clarification
