### ISSUE TITLE
SOM to identify relationships between variables 

### ISSUE THREAD

**Issue by ArioBattolla** [JustGlowing/minisom#32]
Hi! Thank you very much for sharing this library.
I would like to use SOM to identify correlations between variables. Let's say, I have  an output Y and three variables X1, X2, X3. I train a SOM with features X1, X2, X3, Y and then I would like to plot over the SOM graph the quantities X1, X2, X3, Y (as an heatmap for example). In this way, I could graphically find if there are some relationship between my variables. 
Like this example: https://www.lsoptsupport.com/examples/optimization/multiobjective/self-organizing-maps/multiobjective-34.png 

How can I do that?
Because I found some problems:
1) For each neuron winner, I have many samples. If I want to plot the variable X1 over this neuron, should I take the mean of all the samples gathered in this neuron?
2) Doing so, I will have some parts undefined of the SOM, where there are looser neurons. How can I do to remove these parts, or better, how can I ensure to have winner neurons everywhere?

Another question is: if I change the value of sigma I have completely different outputs. How can I choose the optimal sigma value? With which criterion should I choose it?

Thank you very much, I will give you a star in advance,

Regards,
Ario

**Comment by JustGlowing** [comment]
Hi Ario,

You want to plot feature planes. This example will solve questions 1 and 2: https://github.com/JustGlowing/minisom/blob/master/examples/DemocracyIndex.ipynb

About the last question, you can optimize the quantization error if you don't have a specific target to optimize.

**Comment by ArioBattolla** [comment]
Great! Thank you very much for your fast replay. I tried and now it is working. I will recommend this module also to my colleagues!
Another question: Have you already implemented some algorithms that look at feature planes and understand which variable are more correlated and which are not? Because if I have 100 variables, it would be great to run this algorithm and have automatically save only the feature planes of important correlations, without that a human has to see every plot. If not, do you have any suggestions how to do that? Are there quantities that compute the similarity between feature planes?

**Comment by JustGlowing** [comment]
If you don't want to do anything too complex, you can just consider a feature plane as a matrix P_feature and compute a sort of correlation index between two features as norm(P_feature1 - P_feature2). This way you can keep only the features that are "correlated" with your Y.

**Comment by ArioBattolla** [comment]
Nice idea. I could start from that!
Last question, then I can close the Issue. 

Regarding the quantization error, I tried to create loops to change sigma and the size in order to minimize it, but actually the feature planes becomes really bad. So, quant error in this case is not a good metrics?

Thank you very much for your great availability :)

**Comment by JustGlowing** [comment]
Not sure what you mean by "bad" in this case, but if you vary sigma make sure that the size of the map is still appropriate.

**Comment by ArioBattolla** [comment]
For interested reader: I found a good way to compute the correlation between two maps. Basically you can flatten the W matrix (the feature plane) in order to obtain a vector for each features. Then, you can compute simply the Spearman or Pearson coefficient between these vectors.

For JustGlowing:
I am sorry to still bother you, but I have a further question for you, hoping you can help me :) 
Is there a way to automatically find the optimal sigma? Because I am comparing my results with a commercial software that generates SOMs on the same data. The results are quite similar, but the commercial software has fixed size, fixed seed, and you can only change the learning rate. So, I guess that sigma is automatically found and I would like to do the same.

**Comment by JustGlowing** [comment]
Hi Ario, I usually set sigma as one third of the size of the map (with a
square map and a gaussian neighbor function). Though, the optimal value
strongly depends on your specific setting and application.
