### ISSUE TITLE
A question about line 270 and 271 in minisom.py

### ISSUE THREAD

**Issue by wyznio** [JustGlowing/minisom#35]
I have a small question about the source code of minisom.py. 
In line 270
```
norm = fast_norm(self._weights[it.multi_index])
```
The variable "norm" is never used in the function of "random_weights_init".
In line 271
```
self._weights[it.multi_index] = self._weights[it.multi_index]
``` 
The variables are the same on both sides of "=". What's the point of assigning a variable to the same variable.

**Comment by JustGlowing** [comment]
good pick, I stopped normalizing the weights few realeases ago and the computation of the norm and the reassignment are useless and I'll delete them asap.
