### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by enthu-sh** [JustGlowing/minisom#37]
I am trying to run statement: from minisom import MiniSom
But I get syntax error: progress = f'\r [ {0:{len(str(m))}} / {m} ] {0:3.0f}% - ? it/s' in minisom.py.

Is there any pre-requisite that I am missing.

**Comment by JustGlowing** [comment]
You get this error because you're using a version of Python lower than 3.6.

To solve you're issue, you can upgrade python version or installing minisom
cloning from the repo (there are instructions for this in the readme).

**Comment by JustGlowing** [comment]
I just released a new version and partially restored compatibility with older versions of Python. I'd recommend you to install minisom with pip now:
`pip install -U minisom`
