### ISSUE TITLE
is it possible to continue training?

### ISSUE THREAD

**Issue by melsener** [JustGlowing/minisom#39]
Hi,
I want to see the change of the output while the SOM is learning. Is it possible to call fit again (to continue training) after it already fitted to some data? I've just tried with some data to do this but there's no significant change between the fits. What can be wrong? 

Thanks.

**Comment by JustGlowing** [comment]
Hi @melsener 

You can use the method update to partially train the SOM: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L230

If you run the training from scratch you can disrupt what you learnt previously because the learning rate is high at the beginning of the process.

**Comment by melsener** [comment]
@JustGlowing i didn't see that the decay function's default value, it makes sense. thank you so much.
