### ISSUE TITLE
Testing and Accuracy

### ISSUE THREAD

**Issue by Sarwat-Fatima** [JustGlowing/minisom#4]
I am using MEG dataset with two labels 1 and 0. Is it possible to perform testing of trained dataset and calculate the classification accuracy score using miniSOM?

**Comment by JustGlowing** [comment]
Hi sarwat, minisom doesn't implement any classification mechanism. If you want test classification accuracy, first you have to implement you classification strategy and then test the accuracy.

For example, you could consider the mapping of the samples provided by minisom as a feature space and apply knn in this space. After that you can compute your classification metric (precision, recall, f1, ...).

**Comment by Sarwat-Fatima** [comment]
Okay. Thankyou. I will try that.
