### ISSUE TITLE
Error in PCA Initialization

### ISSUE THREAD

**Issue by AustinT** [JustGlowing/minisom#40]
The documentation for `pca_weights_init` says that it initializes weights to span the **first** 2 principal components. Yet from the code it looks like it actually uses the **last** 2 principal components. Is this the intended behaviour? (I believe it is a mistake).

Specifically, [here](https://github.com/JustGlowing/minisom/blob/e358ae397148e121f87d437b3bd188eae8668f91/minisom.py#L289) you use argsort, which will sort the eigenvalues from **least to greatest**. Then [here](https://github.com/JustGlowing/minisom/blob/e358ae397148e121f87d437b3bd188eae8668f91/minisom.py#L292) you take the first and second values, which would be the least and second least principal components. At least in my experience, the _first n_ principal components are the ones with the n _greatest_ eigenvalues (not _least_), which is why I believe this is a mistake.

This would have escaped your unit tests [here](https://github.com/JustGlowing/minisom/blob/e358ae397148e121f87d437b3bd188eae8668f91/minisom.py#L548) because you tested only in 2D.

If it is a mistake, it could be fixed by changing 0, 1 to [-1, -2] [here](https://github.com/JustGlowing/minisom/blob/e358ae397148e121f87d437b3bd188eae8668f91/minisom.py#L292). I can submit a PR if you would like.

**Comment by JustGlowing** [comment]
hi @AustinT, well spotted. I just fixed the issues. If you pull from master now the correct principal components are used.
