### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by amjramjr** [JustGlowing/minisom#46]
Hi,
I guess there are some initialization errors in train_random() as the attached image.
Regards,
amjr

![minisom_error](https://user-images.githubusercontent.com/51914286/66074693-2bf24780-e530-11e9-9ade-27abb3346568.jpg)

**Comment by JustGlowing** [comment]
hi @amjramjr thanks for reporting the issue. I'll push a fix later today. In the meanwhile you cat set the parameter verbose to False so that you can run your training.

**Comment by amjramjr** [comment]
> I just pushed a fix, you can install the current version as follows:
> 
> ```
> git clone https://github.com/JustGlowing/minisom.git
> python setup.py install
> ```
> 
> Please let me know if your try it because I can't replicate your error.

Thank´s @JustGlowing ...just installed !

**Comment by JustGlowing** [comment]
did it work?

**Comment by amjramjr** [comment]
> did it work?

Yes. It worked !
