### ISSUE TITLE
Number formating error

### ISSUE THREAD

**Issue by amjramjr** [JustGlowing/minisom#47]
It seems there´s some formating error in verbose routine.
I happens sometimes:

![ErrorVerboseMiniSom](https://user-images.githubusercontent.com/51914286/66237708-2cbfe080-e6cc-11e9-9f6a-d5bc670f9710.jpg)

**Comment by JustGlowing** [comment]
Can you tell me more about your settings? Which version of Python and OS are you using?

**Comment by amjramjr** [comment]
Win8.1 Pro. Python 3.7.4

**Comment by JustGlowing** [comment]
Thanks for the info.

I don't seem to be able to replicate the issue. For the moment I removed the `it/s` estimation so that no division by a very small number is performed. Hopefully I'll reintroduce it in the future.

I hope minisom was of help to your study/research.

**Comment by amjramjr** [comment]
Thanks @JustGlowing, Minisom is a great tool to perform my analysis, I´m integrating it with big ERP systems, and it´s running quite well.
