### ISSUE TITLE
Difference between train_random and train_batch methods?

### ISSUE THREAD

**Issue by FlorentF9** [JustGlowing/minisom#48]
Hi,

Looking at the code, it seems that there is no difference between the `train_random` and `train_batch` methods:

```python
def train_random(self, data, num_iteration, verbose=False):
    self.train(data, num_iteration, random_order=False, verbose=verbose)

def train_batch(self, data, num_iteration, verbose=False):
    self.train(data, num_iteration, random_order=False, verbose=verbose)
``` 

I think `train_random` should call the `train` method with `random_order=True`, right?

**Comment by JustGlowing** [comment]
Thank you, I just pushed a fix. Notice that if you installed minisom with pip, the method `train` is not available yet.
