### ISSUE TITLE
[Question] Styling like R

### ISSUE THREAD

**Issue by mafar** [JustGlowing/minisom#49]
Possible to build plot like this ? 
Can anyone please post an example in https://github.com/JustGlowing/minisom/tree/master/examples

**Reference:** https://www.r-bloggers.com/self-organising-maps-for-customer-segmentation-using-r/

![SOM](https://user-images.githubusercontent.com/4101480/69218334-52c51580-0b92-11ea-8d4f-3bfa6747c7a6.png)

**Comment by JustGlowing** [comment]
hi @mafar,

Unfortunately, Minisom doesn't implement hexagonal topologies.

**Comment by mafar** [comment]
thankx  for answer 
+1 for request
