### ISSUE TITLE
KeyError: 0 when initializing random weights

### ISSUE THREAD

**Issue by TimNagle-McNaughton** [JustGlowing/minisom#50]
Encountering a Key Error: 0 when trying to initialize weights. 

Hopefully I'm just misunderstanding what kind of data can be passed to the random_weights_init. 

Any help much appreciated.

----

### Data
Shape: 
(21196800, 6)

Header:
   3x3_high-pass  5x5_high-pass  Scharr_X  Scharr_Y    Std_dev  Original
0          426.0        -2403.0     -63.0    -177.0  14.036022     361.0
1          388.0        -2458.0      -8.0     -50.0  14.478539     359.0
2          405.0        -2432.0      31.0     -19.0  13.921394     360.0
3          440.0        -2348.0      87.0     -95.0  14.062276     361.0
4          436.0        -2259.0     219.0       9.0  13.603740     357.0

----

### Code

`data = pd.read_csv("C:/Mars/output.txt", names = ["3x3_high-pass",  "5x5_high-pass", "Scharr_X", "Scharr_Y",  "Std dev",  "Original"],  index_col = False,  low_memory = True,  na_values = 0.0, na_filter = True)`

`som_grid_rows = 10`

`som_grid_columns = 10 `

`iterations = 500`

`sigma = 1`

`learning_rate = 1`

`som = MiniSom(x = som_grid_rows,
             y = som_grid_columns,
             input_len = data.shape[1],
             sigma = sigma,
             learning_rate = learning_rate)`

`som.random_weights_init(data)`

`starting_weights = som.get_weights().copy()`

`start_time = time.time()`

`som.train(data, iterations)`

`elapsed_time = time.time() - start_time`

`print(elapsed_time)`

----

### Error

KeyError                                  Traceback (most recent call last)
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-21-23bb35759064> in <module>
     14 
     15 # initialize weights
---> 16 som.random_weights_init(data)
     17 
     18 # save the starting weights

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\minisom.py in random_weights_init(self, data)
    270         """Initializes the weights of the SOM
    271         picking random samples from data."""
--> 272         self._check_input_len(data)
    273         it = nditer(self._activation_map, flags=['multi_index'])
    274         while not it.finished:

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\minisom.py in _check_input_len(self, data)
    224     def _check_input_len(self, data):
    225         """Checks that the data in input is of the correct shape."""
--> 226         data_len = len(data[0])
    227         if self._input_len != data_len:
    228             msg = 'Received %d features, expected %d.' % (data_len,

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2925             if self.columns.nlevels > 1:
   2926                 return self._getitem_multilevel(key)
-> 2927             indexer = self.columns.get_loc(key)
   2928             if is_integer(indexer):
   2929                 indexer = [indexer]

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2657                 return self._engine.get_loc(key)
   2658             except KeyError:
-> 2659                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2660         indexer = self.get_indexer([key], method=method, tolerance=tolerance)
   2661         if indexer.ndim > 1 or indexer.size > 1:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 0

**Comment by JustGlowing** [comment]
Hi there, you're passing a pandas dataframe while the method expects numpy
array or a list.

Try converting your data as follows:

`data = data.values`

Let me know if it works ;)

**Comment by TimNagle-McNaughton** [comment]
Yep that did it, thanks very much! Sorry for the bother -- your work is greatly appreciated.

**Comment by JustGlowing** [comment]
No problemo! Leave a star if minisom turns out to be useful.
