### ISSUE TITLE
to show the neurons description

### ISSUE THREAD

**Issue by otmanad** [JustGlowing/minisom#52]
Hi,
There are a function to show the elements of each neuron (the words in the case of textmining ) rather than the marks ?

Thanks

**Comment by JustGlowing** [comment]
Hi @otmanad,

You can give a look at this example: https://github.com/JustGlowing/minisom/blob/master/examples/TopicModeling.ipynb

**Comment by otmanad** [comment]
thank you @JustGlowing for your quick reply. I will test your proposal.

Thanks
