### ISSUE TITLE
Question: How can I extract MiniSOM output?

### ISSUE THREAD

**Issue by fletchke** [JustGlowing/minisom#54]
I'm trying to use a MiniSOM as a data pre-processing tool. I've scaled my data, 33 features and 40,516 records, and trained a 202-by-202 MiniSOM with it.

I'm trying to extract a numeric representation of each record's location on the map so I can append it to my data set and feed it to another model.  Is there a command to printout each records's coordinates on the map?

Thank's in advance for your help, most of the examples I've found are focused on generating graphical output

**Comment by JustGlowing** [comment]
Hi there, you can use the method `winner` to compute the coordinates of the
location of the map for a given record.
