### ISSUE TITLE
Generating the clustering results using Minisom

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [JustGlowing/minisom#58]
How can I generate the clustering results using minisom i.e. which data point belongs to which cluster? For eg: In the case of the Iris data set, I want to generate a file wherein each data point gets classified to a particular type (a cluster# in case of clustering).

How can I achieve this using minisom?

I would be highly grateful to you for your kind help. Thanks in advance.

**Comment by JustGlowing** [comment]
hi @soumya-ranjan-sahoo, this question has been already answered here: https://github.com/JustGlowing/minisom/issues/25

**Comment by soumya-ranjan-sahoo** [comment]
Hi Team,

Thanks for a prompt response. I might need some more clarity on this one - For instance, if I want to cluster my data points into n-clusters,  I need to design the SOM with n*1 nodes on the output map? How about having an n*m map where data points belonging to the same cluster are spread across the grid (Eg. in Iris data set, let's say orange, green and blue are 3 clusters and they are spread across the grid i.e. multiple nodes have orange clusters. How do we go about this?)

**Comment by JustGlowing** [comment]
Then you have to treat the coordinates on the map as features and use another clustering algorithm to get the clusters.

**Comment by soumya-ranjan-sahoo** [comment]
If I treat the coordinates as features, then the grid-based distance between the nodes might be the same for positive as well as the negative class datapoints.  For instance, let's have 3 nodes (0,0),(0,1),(0,2) with 2 classes. Class 1 might be mapped to (0,0) and (0,1), while class 2 gets mapped to (0,2). In this case, taking (i,j) coordinates as features how do I differentiate between 2 class as the distance between (0,0) and (0,1) is the same as (0,1) and (0,2). 

Also, if I want to cluster my data points into n-clusters, do you recommend using a 1-D som of shape (1,n) where n = number of clusters? 

Thanks in advance!

**Comment by JustGlowing** [comment]
Hi again @soumya-ranjan-sahoo,

In the case that you described, where two the classes are equidistant, you should pick one at random unless you have some prior knowledge on the problem. 

About the map size:

- If you want to cluster on the space created by the som, I'd recommend you to create a square map. Possibly large enough to map a sample per cell.
- If you want to use a small map, just consider each neuron as a cluster (as suggested in https://github.com/JustGlowing/minisom/issues/25)

**Comment by JustGlowing** [comment]
hi there, I made this example to show how to use minisom for clustering:

https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

**Comment by akol67** [comment]
then, in theory, you may use these clusters as input to a supervised SOM...
