### ISSUE TITLE
Trying to reproduce color mapping example.

### ISSUE THREAD

**Issue by rbeucher** [JustGlowing/minisom#59]
Hi,

I just found out about Minisom so my apologies if I am missing something obvious.

I have been trying to reproduce the following example:
[http://www.pymvpa.org/examples/som.html](http://www.pymvpa.org/examples/som.html)

Here is my attempt using Minisom:

```import numpy as np

#Training inputs for RGBcolors
colors = np.array(
     [[0., 0., 0.],
      [0., 0., 1.],
      [0., 0., 0.5],
      [0.125, 0.529, 1.0],
      [0.33, 0.4, 0.67],
      [0.6, 0.5, 1.0],
      [0., 1., 0.],
      [1., 0., 0.],
      [0., 1., 1.],
      [1., 0., 1.],
      [1., 1., 0.],
      [1., 1., 1.],
      [.33, .33, .33],
      [.5, .5, .5],
      [.66, .66, .66]])
color_names = \
    ['black', 'blue', 'darkblue', 'skyblue',
     'greyblue', 'lilac', 'green', 'red',
     'cyan', 'violet', 'yellow', 'white',
     'darkgrey', 'mediumgrey', 'lightgrey']

from minisom import MiniSom    
som = MiniSom(20, 30, 3, sigma=0.3, learning_rate=0.3)
som.train_random(colors, 4000, verbose=True)
```
I am trying to visualize things,
Not that the weights have a -1, 1 range. Is that normal?

```
import matplotlib.pyplot as plt

im = plt.imshow(abs(som.get_weights()), interpolation='none')
```

output image do not show any clustering, just look like noise.

What am I doing wrong?

Thanks!

**Comment by JustGlowing** [comment]
Hi @rbeucher ,

The value of sigma that you are using is too low.

I added your snippet among the usage examples of Minisom using a higher value for sigma:
https://github.com/JustGlowing/minisom/blob/master/examples/ColorSpaceMapping.ipynb

It's quite interesting to see how the result changes when the neighbourhood function changes.

Thanks for using Minisom ;-)

**Comment by rbeucher** [comment]
Great, Thanks!
