### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by V-for-Vaggelis** [JustGlowing/minisom#60]
Is there an example or guideline on how to achieve feture selection on high-dimensional data with minisom?

**Comment by JustGlowing** [comment]
hi @V-for-Vaggelis ,

It's not impossible to do features selection in a straightforward fashion with SOM but I'm not aware of any popular method to do so. However, it's worth to have a look into feature planes (or feature maps). Here's an example:

https://github.com/JustGlowing/minisom/blob/master/examples/DemocracyIndex.ipynb

As you can see from the charts, the weights for a specific feature can have specific shapes in the SOM. Features that are redundant either have a flat shape or a shape that is very similar to another feature. Also, if your weights are all positive, you can draw a map of the "most relevant" features (see the last chart in the example). Features that don't show on this map can be discarded.

I hope this helps.

**Comment by V-for-Vaggelis** [comment]
Actually @JustGlowing  this is very helpful. So in this case we could discard: democracy_index and civil_liberties because they don't show much in the most relevant feature plane, and there was an indication for that because their individual feature planes look a lot like the one for electoral_procces_pluralism.

**Comment by JustGlowing** [comment]
Let's say that you could have similar results removing `electoral_procces_pluralism` and `civil_liberties`. Consider that this dataset is pretty simple as the features are all highly correlated.

**Comment by V-for-Vaggelis** [comment]
@JustGlowing why removing `electoral_procces_pluralism`? It seems to show a lot on the feature plane

**Comment by JustGlowing** [comment]
It does, but if you can see a similar shape also in other features. If you draw a scatter matrix of the data you would realize.

**Comment by V-for-Vaggelis** [comment]
Hi again @JustGlowing  . After talking about this with a professor of mine I learned that he and an associate have published a paper suggesting an algorithm on how to do feature selection via SOM. There is already an implementation in MATLAB and I am planning to create one for python. If you gave me a pull request I would be happy to try and contribute by adding this as an example in minisom :)

**Comment by JustGlowing** [comment]
hi @V-for-Vaggelis , it would be great to have the example! I can't open a pull request for you but you can follow this guide: https://opensource.com/article/19/7/create-pull-request-github

The examples are all organized in notebooks and are stored in this folder: https://github.com/JustGlowing/minisom/tree/master/examples
