### ISSUE TITLE
Quantization error calculation

### ISSUE THREAD

**Issue by aortizg** [JustGlowing/minisom#62]
In function "quantization_error", it is computed as power((self.quantization(data) - data), 2).mean() making the mean between components instead of the average for all samples. 
You can reproduce the issue using data as one-sample array.

**Comment by JustGlowing** [comment]
hi @aortizg 

This looks fine to me:

![image](https://user-images.githubusercontent.com/4929177/75228695-6642d680-57a8-11ea-88d2-6fa78cb11b5b.png)

**Comment by aortizg** [comment]
Quantization error is the mean distance from each data sample to their corresponding bmu. Are you sure is that implemented?

**Comment by JustGlowing** [comment]
As you can see `power((self.quantization(data) - data), 2)` computes the distance from the bmu (returned by `self.quantization(data)`) and `mean()` takes the average of all the distances value by value.

**Comment by aortizg** [comment]
Sorry, but I don't agree. 
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.power(a-b,2)=([16, 16, 16, 16])
so, mean is 16.

To compute the euclidean distance you have to sum the squared difference of the components and take the sqrt. For instance (l2-norm):
distance from a to b : dist = np.linalg.norm(a-b)=8

So, the result is not the same.

**Comment by JustGlowing** [comment]
This example is appreciated. At the time I implemented that function I was following a different definition but I agree that it would be convenient to switch to a more standard one. I'll do it whenever I have some spare time.

Thanks for your contribution.

**Comment by JustGlowing** [comment]
FYI, I just pushed a new version where the quantization error respects the standard definition.
