### ISSUE TITLE
hexagonal grids

### ISSUE THREAD

**Issue by V-for-Vaggelis** [JustGlowing/minisom#63]
A common implementation of the algorithm is often using hexagonal grids instead of square or orthogonal providing interesting results. Is it possible to do something like this with minisom?

**Comment by JustGlowing** [comment]
Hi there, hexagonal grids are not implemented currently. It's on the roadmap but I don't see it happening soon.

**Comment by V-for-Vaggelis** [comment]
Thank you for the response, do you have any advice on optimization techniques I could use to get lower errors for a square grid? For example, setting the grid size so that the number of neurons is close to the number of training points seems to impove the results

**Comment by JustGlowing** [comment]
Yup, have a look at this: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L93

**Comment by V-for-Vaggelis** [comment]
Thanks 😃

**Comment by JustGlowing** [comment]
hi @V-for-Vaggelis 

Somebody adapted minisom to use an hexagonal grid. Here are the extensions they made: https://github.com/murci3lag0/swinsom/blob/8fc0ac15a8959bbbfd4d131048c2b05d06b0ddc3/som.py

**Comment by JustGlowing** [comment]
hi again @V-for-Vaggelis 

Minisom now supports the hexagonal topology. This features has not been released yet, if you want to you you need to pull the latest changes from the master branch.

**Comment by V-for-Vaggelis** [comment]
Thank you @JustGlowing, maybe I'll try it oute when I catch a breath :)
