### ISSUE TITLE
Predict winning cell for new data

### ISSUE THREAD

**Issue by imariasantos** [JustGlowing/minisom#68]
Once the SOM has been trained, is it possible to fit data to the SOM? I haven't found anything like this in the examples.

**Comment by JustGlowing** [comment]
hi @imariasantos, what do you mean by "fit the data"?

Usually training means fitting the data.

**Comment by imariasantos** [comment]
Is it possible to predict what cell from the trained SOM a sample (not used to train the SOM) belongs to ?

**Comment by JustGlowing** [comment]
yes, just like this:
```
som.winner(new_data)
```

This is also used in the Iris example.
