### ISSUE TITLE
Pickling the trained model

### ISSUE THREAD

**Issue by gsvijayraajaa** [JustGlowing/minisom#7]
Hi,

    I am not able to serialise the trained som using python pickle module. I am trying to do the following:

som = MiniSom(4,4,40,sigma=.8,learning_rate=0.5)
som.train_random(Training_data,2000) # random training

output_som = open('som.pickle', 'wb')
pickle.dump(som, output_som, -1)
output_som.close()

I get the following error:
PicklingError: Can't pickle <type 'instancemethod'>: it's not found as __builtin__.instancemethod

Regards,
Vijay Raajaa G S

**Comment by JustGlowing** [comment]
Hi, 

Check out the comments under this post:

http://glowingpython.blogspot.co.uk/2013/09/self-organizing-maps.html?m=1

**Comment by gsvijayraajaa** [comment]
Thanks.. It did work !!
