### ISSUE TITLE
How do I get  the final weights between neurons in the input layer and neurons in the output layer?

### ISSUE THREAD

**Issue by vingol** [JustGlowing/minisom#70]
Hi,
Is there any way I can get the final weights between neurons in the input layer and neurons in the output layer?

**Comment by JustGlowing** [comment]
Hi there, you can get the weights using the method `get_weights`.

**Comment by vingol** [comment]
Thank you so much for replying me quickly, by the way, is there any files or website I can find these functions such as this function `get_weights` or other function I need?

**Comment by JustGlowing** [comment]
Here: https://github.com/JustGlowing/minisom/blob/master/minisom.py

**Comment by vingol** [comment]
Got it! Thanks very much.
