### ISSUE TITLE
How can I visualise The winning neurons and clusters of data points from a TFIDF matrix on text data?

### ISSUE THREAD

**Issue by Daviid1010** [JustGlowing/minisom#72]
Hi there this package is great! I'm trying to model text data into topics and I would like to create a visualization of the data clusters in relation to their winning neurons. Also, have you implemented any performance metrics on the SOM model for comparison against other unsupervised model?

**Comment by JustGlowing** [comment]
Hi @Daviid1010 

There are many ways to visualize clusters of topics. The first idea that comes to my mind is to color each cell with a color assigned to the topic of the majority of the documents mapped in that cell.

Regarding the metrics to compare SOM with other models I would use the ones that are already implemented in sklearn: https://scikit-learn.org/stable/modules/classes.html#clustering-metrics

The metrics above require you to assign a monodimensional cluster index, this example shows you how do it with MiniSom:
https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

**Comment by JustGlowing** [comment]
I'd also recommend you to have a look at this example about topic modelling with minisom: https://github.com/JustGlowing/minisom/blob/master/examples/TopicModeling.ipynb

**Comment by Daviid1010** [comment]
Hi @JustGlowing 

Thats perfect thanks I was topic modelling some documents so this will be really useful thanks very much! The library is great!
