### ISSUE TITLE
why use SOMs when we already have labels?

### ISSUE THREAD

**Issue by Yanjiayork** [JustGlowing/minisom#74]
Hello there,

Excuse me to ask the silly questions and it is really not about the code itself. In the examples folder, there are a lot of examples, such as the basic use example and etc.. The label is already included in the dataset, then why  are we still using SOM to plot the distance map along with the labels. How can that help us or what is the research objective there as I understand SOM is unsupervised learning for unlabelled dataset.

**Comment by JustGlowing** [comment]
Hi there,

SOM is indeed an unsupervised model. If you look at the basic usage documentation, the labels are never used for training but only for displaying the results visually. This is quite common when using SOM for *dimensionality reduction*. You can check it out here:

https://github.com/JustGlowing/minisom/blob/master/examples/BasicUsage.ipynb

However, SOM is a versatile model and, it can also use the labels when available. Here's an example that shows how to perform classification using minisom:

https://github.com/JustGlowing/minisom/blob/master/examples/Classification.ipynb
