### ISSUE TITLE
Is it possible to mark "forbidden" neurons?

### ISSUE THREAD

**Issue by domstoppable** [JustGlowing/minisom#75]
I need to create a hex map, but require a topology where a few specific cells are forbidden/reserved such that none of the data should map there. I suspect that it may be possible to achieve this by modifying weights manually, but I'm not confident on the right way to do that.

Any advice or ideas?

**Comment by JustGlowing** [comment]
hi @domstoppable, thanks for this interesting question.

To prevent neurons from being activated you can set their weights with values outside the range of your data. For example, if your data is normalized to have values in [0, 1], you can set all the weights of your forbidden neuron to -1 at each training iteration.

**Comment by domstoppable** [comment]
That sounds just as simple as I hoped it would be. Thanks!

**Comment by JustGlowing** [comment]
You're welcome. Make sure to use the appropriate sigma if you're trying to create ad hoc regions in som.

**Comment by domstoppable** [comment]
That sounds like an important tip, but I'm a bit uninformed to really appreciate it. Any suggested readings or other resources where I can better understand?

**Comment by JustGlowing** [comment]
You can have a look at the tutorials here: https://github.com/JustGlowing/minisom#other-tutorials
