### ISSUE TITLE
a question about Generate executable file

### ISSUE THREAD

**Issue by suyanman** [JustGlowing/minisom#80]
Hi, I use minisom to do a clustering，and now i want to generate an executable file. I use pyinstaller to do this. But when i open this .exe file,it has a question about "No module named 'minisom'". I don't know how to solve this problem，hope to get your advice.Thank you.

**Comment by JustGlowing** [comment]
hi @suyanman, make sure that pyinstaller is using the Python environment where minisom is installed. It's hard to help without knowing how you setup python, but if you're using the command line this might solve your issue:

```
pip install minisom
pyinstaller your_clustering_code.py
```

**Comment by suyanman** [comment]
It is the problem of environment configuration.Now it has been solved . Thank you very much！

**Comment by JustGlowing** [comment]
You're always welcome.
