### ISSUE TITLE
Does minisom support partial_fit?

### ISSUE THREAD

**Issue by MutianWang** [JustGlowing/minisom#83]
I have a huge dataset, so I want to train them in batch. What will happen if I run som.train() multiple times on different data? Will it do "incremental learning"? Thanks.

**Comment by JustGlowing** [comment]
Hi there, of you use the method `train` on a som that has already been trained, it will use the existing weights as starting point but the decay function will start from its initial value. You can use the method `update` to run each iteration separately and control the decay function via the iterations counter.
