### ISSUE TITLE
How to detect time series pattern by using this algorithm?

### ISSUE THREAD

**Issue by mick-liu** [JustGlowing/minisom#84]
Hello everyone! 

Now I am working on my project that I would like to detect time series pattern given a specific period of time. The example you provided about the time-series is great, but I would like to know more about this issue. There is no clear explanation of the time-series application, so that I was wondering if you can provide more description?

Back to the idea of my project, I was thinking the procedure of the work is to train the model with a time-series data to get the classification or clusters of the patterns. Then use the same length of the test set data to see the accuracy of the model. If the accuracy is high, we could classify any time-series data in the future.

I have no idea if my idea will work with this algorithm, hope some of you can provide me more information about your software. Thanks.

**Comment by JustGlowing** [comment]
hi @CHEYULIU,

In the example about time series Minisom is used on a set of time series of the same length to show that in the final mapping time series that are close in shape are mapped in areas that are close.

If you want to detect a pattern in specific areas of you time series, you need to fix a window of a certain length and train Minisom with samples that represent your window. Of course, you need to move your window in a rolling fashion on your original time series.

I hope this helps.

**Comment by CHEYULIU** [comment]
> 
> 
> hi @CHEYULIU,
> 
> In the example about time series Minisom is used on a set of time series of the same length to show that in the final mapping time series that are close in shape are mapped in areas that are close.
> 
> If you want to detect a pattern in specific areas of you time series, you need to fix a window of a certain length and train Minisom with samples that represent your window. Of course, you need to move your window in a rolling fashion on your original time series.
> 
> I hope this helps.

Thanks, this helps a lot. So with my understanding about the time series example, can I assume that the 8 by 8 grids are the total number of classification in terms of the closeness of each product? If so, how can I match a new product sales trend into one of the categories?

And just for conformation, if I apply rolling window data set, I guess I could treat the different rolling window data the same as the "products sales" in the example, right?

**Comment by JustGlowing** [comment]
> Thanks, this helps a lot. So with my understanding about the time series example, can I assume that the 8 by 8 grids are the total number of classification in terms of the closeness of each product? If so, how can I match a new product sales trend into one of the categories?
 
In that example the time series are grouped in 8x8=64 clusters and there's no classification mechanism. If you want to classify your data with minisom you should look at this other example: https://github.com/JustGlowing/minisom/blob/master/examples/Classification.ipynb

> And just for conformation, if I apply rolling window data set, I guess I could treat the different rolling window data the same as the "products sales" in the example, right?

Yes, each window is a sample on its own.

**Comment by CHEYULIU** [comment]
> In that example the time series are grouped in 8x8=64 clusters and there's no classification mechanism. If you want to classify your data with minisom you should look at this other example: https://github.com/JustGlowing/minisom/blob/master/examples/Classification.ipynb

Got it, I have seen the classification example, but it seems like we need to define the label, which represents the classification, in advance. What I wish is to classify the time-series data into several categories without knowing its label first. Is it possible to do that?

Or if we can label the clusters and make it a classification problem for future use?

**Comment by JustGlowing** [comment]
Yes, you can. You have to train your SOM setting the number of neurons as the number of categories that you want (in the example you have 8x8=64 categories). When a new sample arrives you have to check in which neuron it's mapped and this will tell you the category.

**Comment by CHEYULIU** [comment]
> Yes, you can. You have to train your SOM setting the number of neurons as the number of categories that you want (in the example you have 8x8=64 categories). When a new sample arrives you have to check in which neuron it's mapped and this will tell you the category.

This is the sample code I tried to map a new time series data into pre-defined categories. 

```python 
# step 1. get the label for the clusters
winner_coordinates = np.array([som.winner(x) for x in data]).T
cluster_index = np.ravel_multi_index(winner_coordinates, (8,8))  # label for clusters

# step 2. make a new time series data
new_data = data[0].copy()
np.random.shuffle(new_data)

# step 3. find out which category the new data belongs to
winmap = som.labels_map(data, cluster_index)
win_position = som.winner(new_data)
```

It seems to work well, but I have another problem which is about how to set the number of the neuron (in the case we have 8x8 neurons)? In your code docstring, the recommended neuron dimension is 5 x sqrt(samples). Is there a better way to set the parameter or is there a chance to make the algorithm to set the number of neuron by itself?

**Comment by JustGlowing** [comment]
> It seems to work well, but I have another problem which is about how to set the number of the neuron (in the case we have 8x8 neurons)? In your code docstring, the recommended neuron dimension is 5 x sqrt(samples). Is there a better way to set the parameter or is there a chance to make the algorithm to set the number of neuron by itself?

The docstring only suggests a rule of thumb. To get a better model you have to vary the number of neurons and estimate the error for each value.

**Comment by CHEYULIU** [comment]
> The docstring only suggests a rule of thumb. To get a better model you have to vary the number of neurons and estimate the error for each value.

Got it, now I am working on the error estimation part. Just out of curiosity, if the number of sample is large, would the process of the hyper parameter tuning be difficult to do? By the way, is there a pseudo code presenting how to estimate the error for the value between the neurons and new data? Sincerely appreciate your response.

**Comment by JustGlowing** [comment]
If you have too much data, you can always sub-sample it. Regarding the parameter tuning process and the estimation of the error, this heavily depends on your application and there's no pseudo code.
