### ISSUE TITLE
How to know that the training is good enough?

### ISSUE THREAD

**Issue by xuzhang5788** [JustGlowing/minisom#87]
Thank you for your repo. What are the criteria for convergence? If you can give us an example of hyperparameter tunning, it will help a lot.

**Comment by JustGlowing** [comment]
hi there,

You can have a look at this for you first question: https://github.com/JustGlowing/minisom/issues/66#issuecomment-614780617

Unfortunately creating a general example of hyper-parameters tuning is not straightforward and I invite you to read this conversation: https://github.com/JustGlowing/minisom/issues/28
