### ISSUE TITLE
Confused about _build_iteration_indexes

### ISSUE THREAD

**Issue by alex-l-kong** [JustGlowing/minisom#89]
It's not clear to me how `_build_iteration_indexes` is generating the indices assign to each iteration. Suppose `data_len` is 200000 and `num_iterations` is 100. Then, `iterations` would be set to `arange(num_iterations) % data_len` which is a 1-D numpy array filled with the numbers from 0-99.

When the `update` function is called on `data` for each iteration, we then pass `data[iteration]` as `x` as well as `winner(data[iteration])` as `win`. But it seems like this would only select `data[0]` for iteration 0, `data[1]` for iteration 1, etc. It would appear that we're only training on single data points, starting with the 0th row in data and going up to the 99th row if `num_iteration=100`.

Is this expected behavior? Perhaps I'm not understanding something correctly, but I would appreciate a clarification.

UPDATE: checked a previous issue, seems like you need to set num iterations to be at least the same as the number of data points if you want each data point to be seen at least once.

A concluding question: is it possible to support batch training in the future (rather than just on one data point at a time)?

**Comment by JustGlowing** [comment]
hi @alex-l-kong 

> When the update function is called on data for each iteration, we then pass data[iteration] as x as well as winner(data[iteration]) as win. But it seems like this would only select data[0] for iteration 0, data[1] for iteration 1, etc. It would appear that we're only training on single data points, starting with the 0th row in data and going up to the 99th row if num_iteration=100.
> 
> Is this expected behavior? Perhaps I'm not understanding something correctly, but I would appreciate a clarification.
> 

Yes, it is the expected behavior. The first sample has index 0 as indexing starts from 0 in Python. And you guessed correctly, each iteration considers one sample at the time. This is also documented here: https://github.com/JustGlowing/minisom/blob/master/minisom.py#L381

> UPDATE: checked a previous issue, seems like you need to set num iterations to be at least the same as the number of data points if you want each data point to be seen at least once.
> 

Correct.

> A concluding question: is it possible to support batch training in the future (rather than just on one data point at a time)?
> 

There are different definitions of batch training for SOM. I might implement the training methodology that you are referring to, If you point me out the paper that explains it.
