### ISSUE TITLE
How to cluster images?

### ISSUE THREAD

**Issue by balavenkatesh3322** [JustGlowing/minisom#90]
I would like to know how to cluster images instead of reading CSV I want to read all images from disk and cluster those images using SOM.

Can you please share some examples?

**Comment by JustGlowing** [comment]
Hi @balavenkatesh3322 ,

This example does exactly what you asked for: https://github.com/JustGlowing/minisom/blob/master/examples/HandwrittenDigits.ipynb

This one is about clustering:
https://github.com/JustGlowing/minisom/blob/master/examples/Clustering.ipynb

**Comment by balavenkatesh3322** [comment]
@JustGlowing Thanks for responding. when i changed my image dateset i get killed message.even it's not executing completely. Do you have any idea to solve this issue?

**Comment by balavenkatesh3322** [comment]
![Screenshot from 2020-11-23 14-02-23](https://user-images.githubusercontent.com/24771457/99932959-9994af00-2d94-11eb-895b-d1332a514791.png)

**Comment by JustGlowing** [comment]
Very hard to say why you get that error. Try to figure out in which line of your script it's triggered.

**Comment by balavenkatesh3322** [comment]
@JustGlowing when i run 
data = scaler.fit_transform(data). this line only it get killed

**Comment by balavenkatesh3322** [comment]
![Screenshot from 2020-11-23 15-26-31](https://user-images.githubusercontent.com/24771457/99937272-46c0f480-2da0-11eb-8456-6947ad4a39e1.png)

**Comment by balavenkatesh3322** [comment]
som = MiniSom(h, w, len(data[0]), learning_rate=0.5,
              sigma=3, neighborhood_function='triangle')

The above code also getting killed.

**Comment by JustGlowing** [comment]
`scaler.fit_transform(data)` is from sklearn and my best guess is that you just run out of memory.

Have a look here: https://forum.qiime2.org/t/classify-sklearn-killed-9-output/1078/19

Try loading less data and see if it works.

**Comment by balavenkatesh3322** [comment]
@JustGlowing let me share my images with you. can you please take look. THanks

**Comment by JustGlowing** [comment]
You don't need to share your images. Try to see if the you're actually running out of memory loading less data.
