### ISSUE TITLE
How to concatanate SOM output and AutoEncoders output

### ISSUE THREAD

**Issue by aktaseren** [JustGlowing/minisom#92]
For my research, I am trying to concatenate som generated low-dimensional representation by minisom output into autoencoder generated low-dimensional representation. Do you have any suggestion for extracting the related output from minisom?

**Comment by JustGlowing** [comment]
hi @aktaseren 

This will answer your question: https://github.com/JustGlowing/minisom/issues/54

Good luck with your research!

**Comment by aktaseren** [comment]
@JustGlowing Great. I will try this on my research. Thanks for this.
