### ISSUE TITLE
AttributeError: 'XPySom' object has no attribute '_sq_weights_gpu'

### ISSUE THREAD

**Issue by codechrl** [JustGlowing/minisom#93]
Got an error after training the model, using the same code from minisom to get the winner coordinates:
`winner_coordinates = np.array([som.winner(z) for z in data]).T`

got an error msg:

> AttributeError: 'XPySom' object has no attribute '_sq_weights_gpu'

**Comment by JustGlowing** [comment]
Hi there, this error is not from minisom. You are using xpysom, it's a fork of minisom and you can find support for it from it's developers here https://github.com/Manciukic/xpysom
