### ISSUE TITLE
New way of calculating quantization error

### ISSUE THREAD

**Issue by ricardomourarpm** [JustGlowing/minisom#94]
Having made some experiences with minisom, I was faced with a problem, low memory ram when quantization error is needed (you save all records for distances from nodes to instance and can get big).

Thus I made this function, that partition the error.

Please take a look and you may consider!

def partitioned_quant_error(data,som,chunks):
    n=len(data)
    n_chunks = list(range(0,n,chunks))
    n_chunks.append(n)
    errorq=0
    #errorq2=som.quantization_error(data_norm)
    for j in range(len(n_chunks)-1):
        interval = n_chunks[j+1]-n_chunks[j]
        errorq = errorq+som.quantization_error(data_norm[n_chunks[j]:n_chunks[j+1]])*interval/n
    return errorq

**Comment by ricardomourarpm** [comment]
By the way why not including something like this for hexa topographic error:

def get_coordinates_from_index(n, x, y):
    if n<0:
        return(-1,-1)
    return(n%y, int(n/y))

def get_index_from_coordinates(c, x, y):
    if c[0]<0 or c[1]<0 or c[0]>y or c[1]>x:
        return(-1)
    return(c[1]*y + c[0])

def get_neighbors_from_index(n, x, y):
    c = get_coordinates_from_index(n, x, y)
    offset_x = -1 if c[1]%2==0 else 1
    neighbors_c =[(c[0]-1,c[1]), (c[0]+1,c[1]), (c[0],c[1]-1), (c[0]+offset_x,c[1]-1), (c[0],c[1]+1), 
                  (c[0]+offset_x,c[1]+1)] 
    neighbors_c = list(filter(lambda c: (c[0]>=0) and (c[1]>=0) and (c[1]<x) and (c[0]<y), neighbors_c))
    neighbors = list(map(lambda c: get_index_from_coordinates(c, x, y), neighbors_c))
    return list(set(neighbors))

def calculate_topographical_error(som, data):
    bmus_1st_and_2nd = np.argsort(som._distance_from_weights(data), axis=1)[:, :2]
    n_rows = som._weights.shape[0]
    n_columns = som._weights.shape[1]
    neighbors=list(map(lambda t:get_neighbors_from_index(t, n_rows, n_columns), bmus_1st_and_2nd[:,0]))

    e_t=1-np.mean([second in neighs for (second,neighs) in zip(bmus_1st_and_2nd[:,1], neighbors)])
    return(e_t)

def partitioned_topo_error(data,som,chunks):
    n=len(data)
    n_chunks = list(range(0,n,chunks))
    n_chunks.append(n)
    errort=0
    #errorq2=som.quantization_error(data_norm)
    for j in range(len(n_chunks)-1):
        interval = n_chunks[j+1]-n_chunks[j]
        errort = errort+calculate_topographical_error(som,data_norm[n_chunks[j]:n_chunks[j+1]])*interval/n
    return errort

**Comment by JustGlowing** [comment]
Hi @ricardomourarpm this seems like good work but it's hard to evaluate this way. If you want me to have a look, you'll have to raise a pull request.
