### ISSUE TITLE
Something wrong with the gaussian neighborhood function????

### ISSUE THREAD

**Issue by YongchangHu** [JustGlowing/minisom#95]
https://github.com/JustGlowing/minisom/blob/5005a71f4983e8b34d23d7474ea8bdcafa4b30ed/minisom.py#L246-L251

There seems to be an additional Pi in the calculation of Gaussian function.....
Check this...
![guassian](https://user-images.githubusercontent.com/3226931/108792937-6218e700-75bd-11eb-9b79-021602f25085.png)

**Comment by JustGlowing** [comment]
well spotted, thank you.

A fix has just been pushed.
