### ISSUE TITLE
Can this be used for community detection in graphs?

### ISSUE THREAD

**Issue by atheeraa** [JustGlowing/minisom#97]
Hello, 
thank you for sharing your amazing work, 
Can you please tell me if it's possible to using minisom for a community detection clustering task?

**Comment by JustGlowing** [comment]
You could use it to cluster the rows of the adjacency matrix of the users.

**Comment by atheeraa** [comment]
I tried to feed cora.csv network to your clustering example but got : 
loop of ufunc does not support argument 0 of type float which has no callable sqrt method

**Comment by JustGlowing** [comment]
Quite hard to help you with these details.

**Comment by atheeraa** [comment]
Thank you for replying
