### ISSUE TITLE
Request - Change the license

### ISSUE THREAD

**Issue by JanDeDobbeleer** [JustGlowing/minisom#99]
Hi @JustGlowing, I have a quick question. We're about to use minisom in our product at [TrendMiner](https://www.trendminer.com) and are blocked on the Creative Common license as it's not "common" to use that one within software engineering. Are you open to changing it to a more standard one like MIT?

Some context can be found [here](https://opensource.stackexchange.com/questions/777/why-shouldnt-creative-commons-licenses-be-used-for-software).

**Comment by JustGlowing** [comment]
hi @JanDeDobbeleer, I'm considering changing the license but I'm not ready yet. However, I can give to TrendMiner a copy of MiniSom under a different license.

**Comment by JanDeDobbeleer** [comment]
@JustGlowing thank you so much for your swift response. I'll let you work out the details with @jorisgillis, he's in charge of embedding minisom into our stack.

**Comment by jorisgillis** [comment]
Hi @JustGlowing , how can you provide us with a copy under a different license? What license would you prefer? For us MIT or Apache 2.0 are good options.

**Comment by JustGlowing** [comment]
@jorisgillis I reached out via email.
